// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: clairveil/privacy/v2/query.proto

package privacyv2

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryAuditKeyRequest struct {
	Epoch uint64 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
}

func (m *QueryAuditKeyRequest) Reset()         { *m = QueryAuditKeyRequest{} }
func (m *QueryAuditKeyRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAuditKeyRequest) ProtoMessage()    {}
func (*QueryAuditKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b8b20e7e9fa6a70, []int{0}
}
func (m *QueryAuditKeyRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAuditKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAuditKeyRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAuditKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAuditKeyRequest.Merge(m, src)
}
func (m *QueryAuditKeyRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAuditKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAuditKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAuditKeyRequest proto.InternalMessageInfo

func (m *QueryAuditKeyRequest) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

type QueryAuditRecordResponse struct {
	Record      []byte `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	StoreKey    []byte `protobuf:"bytes,2,opt,name=store_key,json=storeKey,proto3" json:"store_key,omitempty"`
	StateHeight int64  `protobuf:"varint,3,opt,name=state_height,json=stateHeight,proto3" json:"state_height,omitempty"`
}

func (m *QueryAuditRecordResponse) Reset()         { *m = QueryAuditRecordResponse{} }
func (m *QueryAuditRecordResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAuditRecordResponse) ProtoMessage()    {}
func (*QueryAuditRecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b8b20e7e9fa6a70, []int{1}
}
func (m *QueryAuditRecordResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAuditRecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAuditRecordResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAuditRecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAuditRecordResponse.Merge(m, src)
}
func (m *QueryAuditRecordResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAuditRecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAuditRecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAuditRecordResponse proto.InternalMessageInfo

func (m *QueryAuditRecordResponse) GetRecord() []byte {
	if m != nil {
		return m.Record
	}
	return nil
}

func (m *QueryAuditRecordResponse) GetStoreKey() []byte {
	if m != nil {
		return m.StoreKey
	}
	return nil
}

func (m *QueryAuditRecordResponse) GetStateHeight() int64 {
	if m != nil {
		return m.StateHeight
	}
	return 0
}

type QueryAuditKeyScheduleRequest struct {
}

func (m *QueryAuditKeyScheduleRequest) Reset()         { *m = QueryAuditKeyScheduleRequest{} }
func (m *QueryAuditKeyScheduleRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAuditKeyScheduleRequest) ProtoMessage()    {}
func (*QueryAuditKeyScheduleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b8b20e7e9fa6a70, []int{2}
}
func (m *QueryAuditKeyScheduleRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAuditKeyScheduleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAuditKeyScheduleRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAuditKeyScheduleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAuditKeyScheduleRequest.Merge(m, src)
}
func (m *QueryAuditKeyScheduleRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAuditKeyScheduleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAuditKeyScheduleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAuditKeyScheduleRequest proto.InternalMessageInfo

type QueryAuditKeyScheduleResponse struct {
	ActiveEpoch          uint64 `protobuf:"varint,1,opt,name=active_epoch,json=activeEpoch,proto3" json:"active_epoch,omitempty"`
	NextActivationHeight uint64 `protobuf:"varint,2,opt,name=next_activation_height,json=nextActivationHeight,proto3" json:"next_activation_height,omitempty"`
	NextEpoch            uint64 `protobuf:"varint,3,opt,name=next_epoch,json=nextEpoch,proto3" json:"next_epoch,omitempty"`
	Halted               bool   `protobuf:"varint,4,opt,name=halted,proto3" json:"halted,omitempty"`
	StateHeight          int64  `protobuf:"varint,5,opt,name=state_height,json=stateHeight,proto3" json:"state_height,omitempty"`
}

func (m *QueryAuditKeyScheduleResponse) Reset()         { *m = QueryAuditKeyScheduleResponse{} }
func (m *QueryAuditKeyScheduleResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAuditKeyScheduleResponse) ProtoMessage()    {}
func (*QueryAuditKeyScheduleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b8b20e7e9fa6a70, []int{3}
}
func (m *QueryAuditKeyScheduleResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAuditKeyScheduleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAuditKeyScheduleResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAuditKeyScheduleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAuditKeyScheduleResponse.Merge(m, src)
}
func (m *QueryAuditKeyScheduleResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAuditKeyScheduleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAuditKeyScheduleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAuditKeyScheduleResponse proto.InternalMessageInfo

func (m *QueryAuditKeyScheduleResponse) GetActiveEpoch() uint64 {
	if m != nil {
		return m.ActiveEpoch
	}
	return 0
}

func (m *QueryAuditKeyScheduleResponse) GetNextActivationHeight() uint64 {
	if m != nil {
		return m.NextActivationHeight
	}
	return 0
}

func (m *QueryAuditKeyScheduleResponse) GetNextEpoch() uint64 {
	if m != nil {
		return m.NextEpoch
	}
	return 0
}

func (m *QueryAuditKeyScheduleResponse) GetHalted() bool {
	if m != nil {
		return m.Halted
	}
	return false
}

func (m *QueryAuditKeyScheduleResponse) GetStateHeight() int64 {
	if m != nil {
		return m.StateHeight
	}
	return 0
}

type QueryAuditConfigurationRequest struct {
}

func (m *QueryAuditConfigurationRequest) Reset()         { *m = QueryAuditConfigurationRequest{} }
func (m *QueryAuditConfigurationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAuditConfigurationRequest) ProtoMessage()    {}
func (*QueryAuditConfigurationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b8b20e7e9fa6a70, []int{4}
}
func (m *QueryAuditConfigurationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAuditConfigurationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAuditConfigurationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAuditConfigurationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAuditConfigurationRequest.Merge(m, src)
}
func (m *QueryAuditConfigurationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAuditConfigurationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAuditConfigurationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAuditConfigurationRequest proto.InternalMessageInfo

type QueryAuditConfigurationResponse struct {
	NetworkNonce    []byte `protobuf:"bytes,1,opt,name=network_nonce,json=networkNonce,proto3" json:"network_nonce,omitempty"`
	InitialHeight   uint64 `protobuf:"varint,2,opt,name=initial_height,json=initialHeight,proto3" json:"initial_height,omitempty"`
	CircuitIdentity []byte `protobuf:"bytes,3,opt,name=circuit_identity,json=circuitIdentity,proto3" json:"circuit_identity,omitempty"`
	StateHeight     int64  `protobuf:"varint,4,opt,name=state_height,json=stateHeight,proto3" json:"state_height,omitempty"`
}

func (m *QueryAuditConfigurationResponse) Reset()         { *m = QueryAuditConfigurationResponse{} }
func (m *QueryAuditConfigurationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAuditConfigurationResponse) ProtoMessage()    {}
func (*QueryAuditConfigurationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b8b20e7e9fa6a70, []int{5}
}
func (m *QueryAuditConfigurationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAuditConfigurationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAuditConfigurationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAuditConfigurationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAuditConfigurationResponse.Merge(m, src)
}
func (m *QueryAuditConfigurationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAuditConfigurationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAuditConfigurationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAuditConfigurationResponse proto.InternalMessageInfo

func (m *QueryAuditConfigurationResponse) GetNetworkNonce() []byte {
	if m != nil {
		return m.NetworkNonce
	}
	return nil
}

func (m *QueryAuditConfigurationResponse) GetInitialHeight() uint64 {
	if m != nil {
		return m.InitialHeight
	}
	return 0
}

func (m *QueryAuditConfigurationResponse) GetCircuitIdentity() []byte {
	if m != nil {
		return m.CircuitIdentity
	}
	return nil
}

func (m *QueryAuditConfigurationResponse) GetStateHeight() int64 {
	if m != nil {
		return m.StateHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryAuditKeyRequest)(nil), "clairveil.privacy.v2.QueryAuditKeyRequest")
	proto.RegisterType((*QueryAuditRecordResponse)(nil), "clairveil.privacy.v2.QueryAuditRecordResponse")
	proto.RegisterType((*QueryAuditKeyScheduleRequest)(nil), "clairveil.privacy.v2.QueryAuditKeyScheduleRequest")
	proto.RegisterType((*QueryAuditKeyScheduleResponse)(nil), "clairveil.privacy.v2.QueryAuditKeyScheduleResponse")
	proto.RegisterType((*QueryAuditConfigurationRequest)(nil), "clairveil.privacy.v2.QueryAuditConfigurationRequest")
	proto.RegisterType((*QueryAuditConfigurationResponse)(nil), "clairveil.privacy.v2.QueryAuditConfigurationResponse")
}

func init() { proto.RegisterFile("clairveil/privacy/v2/query.proto", fileDescriptor_6b8b20e7e9fa6a70) }

var fileDescriptor_6b8b20e7e9fa6a70 = []byte{
	// 597 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x7b, 0x6d, 0x1a, 0xa5, 0xd7, 0x14, 0xaa, 0x53, 0x14, 0x45, 0xa1, 0x35, 0x69, 0x10,
	0x52, 0x5a, 0xc0, 0x06, 0xb7, 0x4c, 0x48, 0x48, 0x29, 0x54, 0xb4, 0x6a, 0x85, 0x84, 0xcb, 0x80,
	0x58, 0x2c, 0xd7, 0x79, 0xc4, 0xa7, 0x18, 0x9f, 0x6b, 0x9f, 0x4d, 0x2d, 0xc4, 0xc2, 0xc6, 0x86,
	0xc4, 0xc2, 0x97, 0x60, 0x63, 0xe3, 0x0b, 0x30, 0x56, 0xb0, 0x30, 0xa2, 0x84, 0x0f, 0x82, 0x7c,
	0xbe, 0xa4, 0x49, 0x93, 0x52, 0x32, 0xde, 0xef, 0xfe, 0xef, 0xdd, 0xff, 0x9f, 0xf7, 0x62, 0x5c,
	0xb3, 0x5d, 0x8b, 0x06, 0x31, 0x50, 0x57, 0xf3, 0x03, 0x1a, 0x5b, 0x76, 0xa2, 0xc5, 0xba, 0x76,
	0x1c, 0x41, 0x90, 0xa8, 0x7e, 0xc0, 0x38, 0x23, 0xa5, 0x81, 0x42, 0x95, 0x0a, 0x35, 0xd6, 0xab,
	0x2b, 0x6d, 0xc6, 0xda, 0x2e, 0x68, 0x96, 0x4f, 0x35, 0xcb, 0xf3, 0x18, 0xb7, 0x38, 0x65, 0x5e,
	0x98, 0xd5, 0xd4, 0x6f, 0xe3, 0xd2, 0xb3, 0xb4, 0x45, 0x33, 0x6a, 0x51, 0xbe, 0x0f, 0x89, 0x01,
	0xc7, 0x11, 0x84, 0x9c, 0x94, 0xf0, 0x3c, 0xf8, 0xcc, 0x76, 0x2a, 0xa8, 0x86, 0x1a, 0x39, 0x23,
	0x3b, 0xd4, 0x03, 0x5c, 0x39, 0x53, 0x1b, 0x60, 0xb3, 0xa0, 0x65, 0x40, 0xe8, 0x33, 0x2f, 0x04,
	0x52, 0xc6, 0xf9, 0x40, 0x10, 0x51, 0x52, 0x34, 0xe4, 0x89, 0x5c, 0xc3, 0x0b, 0x21, 0x67, 0x01,
	0x98, 0x1d, 0x48, 0x2a, 0xb3, 0xe2, 0xaa, 0x20, 0xc0, 0x3e, 0x24, 0x64, 0x0d, 0x17, 0x43, 0x6e,
	0x71, 0x30, 0x1d, 0xa0, 0x6d, 0x87, 0x57, 0xe6, 0x6a, 0xa8, 0x31, 0x67, 0x2c, 0x0a, 0xb6, 0x2b,
	0x50, 0x5d, 0xc1, 0x2b, 0x23, 0x0e, 0x0f, 0x6d, 0x07, 0x5a, 0x91, 0x0b, 0xd2, 0x69, 0xfd, 0x07,
	0xc2, 0xab, 0x17, 0x08, 0xa4, 0xb3, 0x35, 0x5c, 0xb4, 0x6c, 0x4e, 0x63, 0x30, 0x87, 0x23, 0x2d,
	0x66, 0x6c, 0x27, 0x45, 0x64, 0x0b, 0x97, 0x3d, 0x38, 0xe1, 0xa6, 0x60, 0xe2, 0x07, 0xea, 0x3b,
	0x9a, 0x15, 0xe2, 0x52, 0x7a, 0xdb, 0x1c, 0x5c, 0x66, 0xd6, 0xc8, 0x2a, 0xc6, 0xa2, 0x2a, 0x6b,
	0x3b, 0x27, 0x94, 0x0b, 0x29, 0xc9, 0x9a, 0x96, 0x71, 0xde, 0xb1, 0x5c, 0x0e, 0xad, 0x4a, 0xae,
	0x86, 0x1a, 0x05, 0x43, 0x9e, 0xc6, 0x42, 0xcf, 0x8f, 0x87, 0xae, 0x61, 0xe5, 0x2c, 0xd3, 0x23,
	0xe6, 0xbd, 0xa2, 0xed, 0x28, 0x10, 0x4f, 0xf7, 0x63, 0x7f, 0x43, 0xf8, 0xfa, 0x85, 0x12, 0x19,
	0xfc, 0x06, 0x5e, 0xf2, 0x80, 0xbf, 0x61, 0x41, 0xc7, 0xf4, 0x98, 0x67, 0x83, 0x9c, 0x4c, 0x51,
	0xc2, 0xa7, 0x29, 0x23, 0x37, 0xf1, 0x15, 0xea, 0x51, 0x4e, 0x2d, 0x77, 0x34, 0xf2, 0x92, 0xa4,
	0x32, 0xeb, 0x3a, 0x5e, 0xb6, 0x69, 0x60, 0x47, 0x94, 0x9b, 0xb4, 0x05, 0x1e, 0xa7, 0x3c, 0x11,
	0x89, 0x8b, 0xc6, 0x55, 0xc9, 0xf7, 0x24, 0x1e, 0xcb, 0x97, 0x1b, 0xcb, 0xa7, 0x7f, 0xc8, 0xe1,
	0x79, 0xe1, 0x9e, 0x7c, 0x46, 0xb8, 0xd0, 0x9f, 0x1c, 0xd9, 0x50, 0x27, 0xad, 0xb0, 0x3a, 0x69,
	0x43, 0xab, 0xea, 0x65, 0xda, 0xd1, 0xfd, 0xac, 0xdf, 0x7d, 0xff, 0xf3, 0xcf, 0xa7, 0xd9, 0x0d,
	0xd2, 0xd0, 0x26, 0xfe, 0x91, 0xac, 0xb4, 0x44, 0xeb, 0x40, 0x12, 0x6a, 0x6f, 0xc5, 0x3c, 0xdf,
	0x91, 0x2f, 0x08, 0x2f, 0x9f, 0x5f, 0x2a, 0xa2, 0xff, 0x87, 0xc5, 0x73, 0x2b, 0x5a, 0xdd, 0x9c,
	0xaa, 0x66, 0x4a, 0xbf, 0x66, 0xd8, 0xb7, 0xf6, 0x15, 0x61, 0x32, 0xbe, 0x0d, 0x64, 0xeb, 0xb2,
	0xd7, 0x27, 0xed, 0x57, 0xf5, 0xfe, 0x94, 0x55, 0xd2, 0xf5, 0x3d, 0xe1, 0xfa, 0x16, 0x59, 0xff,
	0x97, 0x6b, 0x7b, 0xb8, 0x74, 0xfb, 0xc5, 0xf7, 0xae, 0x82, 0x4e, 0xbb, 0x0a, 0xfa, 0xdd, 0x55,
	0xd0, 0xc7, 0x9e, 0x32, 0x73, 0xda, 0x53, 0x66, 0x7e, 0xf5, 0x94, 0x99, 0x97, 0x0f, 0xdb, 0x94,
	0x3b, 0xd1, 0x91, 0x6a, 0xb3, 0xd7, 0xda, 0xe3, 0x9d, 0x83, 0xbd, 0x27, 0xbb, 0xcf, 0xef, 0x1c,
	0x34, 0xb7, 0x0f, 0x87, 0x7a, 0x9f, 0x0c, 0xba, 0xf3, 0xc4, 0x87, 0x50, 0x8b, 0xf5, 0x07, 0x12,
	0xc4, 0xfa, 0x51, 0x5e, 0x7c, 0xe3, 0x36, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x43, 0x0b,
	0x4d, 0x3b, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	AuditKey(ctx context.Context, in *QueryAuditKeyRequest, opts ...grpc.CallOption) (*QueryAuditRecordResponse, error)
	AuditKeySchedule(ctx context.Context, in *QueryAuditKeyScheduleRequest, opts ...grpc.CallOption) (*QueryAuditKeyScheduleResponse, error)
	AuditConfiguration(ctx context.Context, in *QueryAuditConfigurationRequest, opts ...grpc.CallOption) (*QueryAuditConfigurationResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) AuditKey(ctx context.Context, in *QueryAuditKeyRequest, opts ...grpc.CallOption) (*QueryAuditRecordResponse, error) {
	out := new(QueryAuditRecordResponse)
	err := c.cc.Invoke(ctx, "/clairveil.privacy.v2.Query/AuditKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AuditKeySchedule(ctx context.Context, in *QueryAuditKeyScheduleRequest, opts ...grpc.CallOption) (*QueryAuditKeyScheduleResponse, error) {
	out := new(QueryAuditKeyScheduleResponse)
	err := c.cc.Invoke(ctx, "/clairveil.privacy.v2.Query/AuditKeySchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AuditConfiguration(ctx context.Context, in *QueryAuditConfigurationRequest, opts ...grpc.CallOption) (*QueryAuditConfigurationResponse, error) {
	out := new(QueryAuditConfigurationResponse)
	err := c.cc.Invoke(ctx, "/clairveil.privacy.v2.Query/AuditConfiguration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	AuditKey(context.Context, *QueryAuditKeyRequest) (*QueryAuditRecordResponse, error)
	AuditKeySchedule(context.Context, *QueryAuditKeyScheduleRequest) (*QueryAuditKeyScheduleResponse, error)
	AuditConfiguration(context.Context, *QueryAuditConfigurationRequest) (*QueryAuditConfigurationResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) AuditKey(ctx context.Context, req *QueryAuditKeyRequest) (*QueryAuditRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuditKey not implemented")
}
func (*UnimplementedQueryServer) AuditKeySchedule(ctx context.Context, req *QueryAuditKeyScheduleRequest) (*QueryAuditKeyScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuditKeySchedule not implemented")
}
func (*UnimplementedQueryServer) AuditConfiguration(ctx context.Context, req *QueryAuditConfigurationRequest) (*QueryAuditConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuditConfiguration not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_AuditKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAuditKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AuditKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clairveil.privacy.v2.Query/AuditKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AuditKey(ctx, req.(*QueryAuditKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AuditKeySchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAuditKeyScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AuditKeySchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clairveil.privacy.v2.Query/AuditKeySchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AuditKeySchedule(ctx, req.(*QueryAuditKeyScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AuditConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAuditConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AuditConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clairveil.privacy.v2.Query/AuditConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AuditConfiguration(ctx, req.(*QueryAuditConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "clairveil.privacy.v2.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuditKey",
			Handler:    _Query_AuditKey_Handler,
		},
		{
			MethodName: "AuditKeySchedule",
			Handler:    _Query_AuditKeySchedule_Handler,
		},
		{
			MethodName: "AuditConfiguration",
			Handler:    _Query_AuditConfiguration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clairveil/privacy/v2/query.proto",
}

func (m *QueryAuditKeyRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAuditKeyRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAuditKeyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Epoch != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryAuditRecordResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAuditRecordResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAuditRecordResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.StateHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.StateHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.StoreKey) > 0 {
		i -= len(m.StoreKey)
		copy(dAtA[i:], m.StoreKey)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.StoreKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Record) > 0 {
		i -= len(m.Record)
		copy(dAtA[i:], m.Record)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Record)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAuditKeyScheduleRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAuditKeyScheduleRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAuditKeyScheduleRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryAuditKeyScheduleResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAuditKeyScheduleResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAuditKeyScheduleResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.StateHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.StateHeight))
		i--
		dAtA[i] = 0x28
	}
	if m.Halted {
		i--
		if m.Halted {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.NextEpoch != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.NextEpoch))
		i--
		dAtA[i] = 0x18
	}
	if m.NextActivationHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.NextActivationHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.ActiveEpoch != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ActiveEpoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryAuditConfigurationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAuditConfigurationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAuditConfigurationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryAuditConfigurationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAuditConfigurationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAuditConfigurationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.StateHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.StateHeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.CircuitIdentity) > 0 {
		i -= len(m.CircuitIdentity)
		copy(dAtA[i:], m.CircuitIdentity)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.CircuitIdentity)))
		i--
		dAtA[i] = 0x1a
	}
	if m.InitialHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.InitialHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.NetworkNonce) > 0 {
		i -= len(m.NetworkNonce)
		copy(dAtA[i:], m.NetworkNonce)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.NetworkNonce)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryAuditKeyRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Epoch != 0 {
		n += 1 + sovQuery(uint64(m.Epoch))
	}
	return n
}

func (m *QueryAuditRecordResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Record)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.StoreKey)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.StateHeight != 0 {
		n += 1 + sovQuery(uint64(m.StateHeight))
	}
	return n
}

func (m *QueryAuditKeyScheduleRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryAuditKeyScheduleResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ActiveEpoch != 0 {
		n += 1 + sovQuery(uint64(m.ActiveEpoch))
	}
	if m.NextActivationHeight != 0 {
		n += 1 + sovQuery(uint64(m.NextActivationHeight))
	}
	if m.NextEpoch != 0 {
		n += 1 + sovQuery(uint64(m.NextEpoch))
	}
	if m.Halted {
		n += 2
	}
	if m.StateHeight != 0 {
		n += 1 + sovQuery(uint64(m.StateHeight))
	}
	return n
}

func (m *QueryAuditConfigurationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryAuditConfigurationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NetworkNonce)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.InitialHeight != 0 {
		n += 1 + sovQuery(uint64(m.InitialHeight))
	}
	l = len(m.CircuitIdentity)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.StateHeight != 0 {
		n += 1 + sovQuery(uint64(m.StateHeight))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryAuditKeyRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAuditKeyRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAuditKeyRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAuditRecordResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAuditRecordResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAuditRecordResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Record", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Record = append(m.Record[:0], dAtA[iNdEx:postIndex]...)
			if m.Record == nil {
				m.Record = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoreKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StoreKey = append(m.StoreKey[:0], dAtA[iNdEx:postIndex]...)
			if m.StoreKey == nil {
				m.StoreKey = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateHeight", wireType)
			}
			m.StateHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StateHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAuditKeyScheduleRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAuditKeyScheduleRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAuditKeyScheduleRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAuditKeyScheduleResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAuditKeyScheduleResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAuditKeyScheduleResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveEpoch", wireType)
			}
			m.ActiveEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActiveEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextActivationHeight", wireType)
			}
			m.NextActivationHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextActivationHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextEpoch", wireType)
			}
			m.NextEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Halted", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Halted = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateHeight", wireType)
			}
			m.StateHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StateHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAuditConfigurationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAuditConfigurationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAuditConfigurationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAuditConfigurationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAuditConfigurationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAuditConfigurationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkNonce", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NetworkNonce = append(m.NetworkNonce[:0], dAtA[iNdEx:postIndex]...)
			if m.NetworkNonce == nil {
				m.NetworkNonce = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialHeight", wireType)
			}
			m.InitialHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InitialHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CircuitIdentity", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CircuitIdentity = append(m.CircuitIdentity[:0], dAtA[iNdEx:postIndex]...)
			if m.CircuitIdentity == nil {
				m.CircuitIdentity = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateHeight", wireType)
			}
			m.StateHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StateHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
