// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: clairveil/privacy/v1/batch_feasibility.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// These messages freeze and measure the Session 2 max wire shape. They are
// not registered with the Msg service and do not authorize a state transition.
type BatchTransferWirePrototypeV1 struct {
	Creator    string                                `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Proof      []byte                                `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	Root       []byte                                `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	Nullifiers [][]byte                              `protobuf:"bytes,4,rep,name=nullifiers,proto3" json:"nullifiers,omitempty"`
	Outputs    []*BatchTransferOutputWirePrototypeV1 `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty"`
	// Canonical lowercase ASCII [a-z0-9][a-z0-9._-]*, 1..64 bytes.
	AuditKeyId                  string `protobuf:"bytes,6,opt,name=audit_key_id,json=auditKeyId,proto3" json:"audit_key_id,omitempty"`
	AuditKeyEpoch               uint64 `protobuf:"varint,7,opt,name=audit_key_epoch,json=auditKeyEpoch,proto3" json:"audit_key_epoch,omitempty"`
	AuditDisclosureTargetPubkey []byte `protobuf:"bytes,8,opt,name=audit_disclosure_target_pubkey,json=auditDisclosureTargetPubkey,proto3" json:"audit_disclosure_target_pubkey,omitempty"`
	ExpiresAtUnix               int64  `protobuf:"varint,9,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
}

func (m *BatchTransferWirePrototypeV1) Reset()         { *m = BatchTransferWirePrototypeV1{} }
func (m *BatchTransferWirePrototypeV1) String() string { return proto.CompactTextString(m) }
func (*BatchTransferWirePrototypeV1) ProtoMessage()    {}
func (*BatchTransferWirePrototypeV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce0974bff04c91f, []int{0}
}
func (m *BatchTransferWirePrototypeV1) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BatchTransferWirePrototypeV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BatchTransferWirePrototypeV1.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BatchTransferWirePrototypeV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchTransferWirePrototypeV1.Merge(m, src)
}
func (m *BatchTransferWirePrototypeV1) XXX_Size() int {
	return m.Size()
}
func (m *BatchTransferWirePrototypeV1) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchTransferWirePrototypeV1.DiscardUnknown(m)
}

var xxx_messageInfo_BatchTransferWirePrototypeV1 proto.InternalMessageInfo

func (m *BatchTransferWirePrototypeV1) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *BatchTransferWirePrototypeV1) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *BatchTransferWirePrototypeV1) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *BatchTransferWirePrototypeV1) GetNullifiers() [][]byte {
	if m != nil {
		return m.Nullifiers
	}
	return nil
}

func (m *BatchTransferWirePrototypeV1) GetOutputs() []*BatchTransferOutputWirePrototypeV1 {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *BatchTransferWirePrototypeV1) GetAuditKeyId() string {
	if m != nil {
		return m.AuditKeyId
	}
	return ""
}

func (m *BatchTransferWirePrototypeV1) GetAuditKeyEpoch() uint64 {
	if m != nil {
		return m.AuditKeyEpoch
	}
	return 0
}

func (m *BatchTransferWirePrototypeV1) GetAuditDisclosureTargetPubkey() []byte {
	if m != nil {
		return m.AuditDisclosureTargetPubkey
	}
	return nil
}

func (m *BatchTransferWirePrototypeV1) GetExpiresAtUnix() int64 {
	if m != nil {
		return m.ExpiresAtUnix
	}
	return 0
}

type BatchTransferOutputWirePrototypeV1 struct {
	Commitment                 []byte             `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
	Ciphertext                 []byte             `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	ViewTag                    []byte             `protobuf:"bytes,3,opt,name=view_tag,json=viewTag,proto3" json:"view_tag,omitempty"`
	UserPrivacyPolicy          uint32             `protobuf:"varint,4,opt,name=user_privacy_policy,json=userPrivacyPolicy,proto3" json:"user_privacy_policy,omitempty"`
	UserDisclosureMode         UserDisclosureMode `protobuf:"varint,5,opt,name=user_disclosure_mode,json=userDisclosureMode,proto3,enum=clairveil.privacy.v1.UserDisclosureMode" json:"user_disclosure_mode,omitempty"`
	UserDisclosureDigest       []byte             `protobuf:"bytes,6,opt,name=user_disclosure_digest,json=userDisclosureDigest,proto3" json:"user_disclosure_digest,omitempty"`
	UserDisclosureTargetPubkey []byte             `protobuf:"bytes,7,opt,name=user_disclosure_target_pubkey,json=userDisclosureTargetPubkey,proto3" json:"user_disclosure_target_pubkey,omitempty"`
	UserDisclosurePayload      []byte             `protobuf:"bytes,8,opt,name=user_disclosure_payload,json=userDisclosurePayload,proto3" json:"user_disclosure_payload,omitempty"`
	FullDisclosureDigest       []byte             `protobuf:"bytes,9,opt,name=full_disclosure_digest,json=fullDisclosureDigest,proto3" json:"full_disclosure_digest,omitempty"`
	AuditDisclosurePayload     []byte             `protobuf:"bytes,10,opt,name=audit_disclosure_payload,json=auditDisclosurePayload,proto3" json:"audit_disclosure_payload,omitempty"`
	SelfViewDisclosurePayload  []byte             `protobuf:"bytes,11,opt,name=self_view_disclosure_payload,json=selfViewDisclosurePayload,proto3" json:"self_view_disclosure_payload,omitempty"`
}

func (m *BatchTransferOutputWirePrototypeV1) Reset()         { *m = BatchTransferOutputWirePrototypeV1{} }
func (m *BatchTransferOutputWirePrototypeV1) String() string { return proto.CompactTextString(m) }
func (*BatchTransferOutputWirePrototypeV1) ProtoMessage()    {}
func (*BatchTransferOutputWirePrototypeV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce0974bff04c91f, []int{1}
}
func (m *BatchTransferOutputWirePrototypeV1) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BatchTransferOutputWirePrototypeV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BatchTransferOutputWirePrototypeV1.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BatchTransferOutputWirePrototypeV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchTransferOutputWirePrototypeV1.Merge(m, src)
}
func (m *BatchTransferOutputWirePrototypeV1) XXX_Size() int {
	return m.Size()
}
func (m *BatchTransferOutputWirePrototypeV1) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchTransferOutputWirePrototypeV1.DiscardUnknown(m)
}

var xxx_messageInfo_BatchTransferOutputWirePrototypeV1 proto.InternalMessageInfo

func (m *BatchTransferOutputWirePrototypeV1) GetCommitment() []byte {
	if m != nil {
		return m.Commitment
	}
	return nil
}

func (m *BatchTransferOutputWirePrototypeV1) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

func (m *BatchTransferOutputWirePrototypeV1) GetViewTag() []byte {
	if m != nil {
		return m.ViewTag
	}
	return nil
}

func (m *BatchTransferOutputWirePrototypeV1) GetUserPrivacyPolicy() uint32 {
	if m != nil {
		return m.UserPrivacyPolicy
	}
	return 0
}

func (m *BatchTransferOutputWirePrototypeV1) GetUserDisclosureMode() UserDisclosureMode {
	if m != nil {
		return m.UserDisclosureMode
	}
	return UserDisclosureMode_USER_DISCLOSURE_MODE_NONE
}

func (m *BatchTransferOutputWirePrototypeV1) GetUserDisclosureDigest() []byte {
	if m != nil {
		return m.UserDisclosureDigest
	}
	return nil
}

func (m *BatchTransferOutputWirePrototypeV1) GetUserDisclosureTargetPubkey() []byte {
	if m != nil {
		return m.UserDisclosureTargetPubkey
	}
	return nil
}

func (m *BatchTransferOutputWirePrototypeV1) GetUserDisclosurePayload() []byte {
	if m != nil {
		return m.UserDisclosurePayload
	}
	return nil
}

func (m *BatchTransferOutputWirePrototypeV1) GetFullDisclosureDigest() []byte {
	if m != nil {
		return m.FullDisclosureDigest
	}
	return nil
}

func (m *BatchTransferOutputWirePrototypeV1) GetAuditDisclosurePayload() []byte {
	if m != nil {
		return m.AuditDisclosurePayload
	}
	return nil
}

func (m *BatchTransferOutputWirePrototypeV1) GetSelfViewDisclosurePayload() []byte {
	if m != nil {
		return m.SelfViewDisclosurePayload
	}
	return nil
}

// BatchMinimalEventWirePrototypeV1 measures the binary form of the summary
// attributes. No ciphertext, disclosure payload, or full value list appears.
type BatchMinimalEventWirePrototypeV1 struct {
	EffectId           []byte `protobuf:"bytes,1,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"`
	Relayer            string `protobuf:"bytes,2,opt,name=relayer,proto3" json:"relayer,omitempty"`
	InputCount         uint32 `protobuf:"varint,3,opt,name=input_count,json=inputCount,proto3" json:"input_count,omitempty"`
	OutputCount        uint32 `protobuf:"varint,4,opt,name=output_count,json=outputCount,proto3" json:"output_count,omitempty"`
	NullifierRoot      []byte `protobuf:"bytes,5,opt,name=nullifier_root,json=nullifierRoot,proto3" json:"nullifier_root,omitempty"`
	CommitmentRoot     []byte `protobuf:"bytes,6,opt,name=commitment_root,json=commitmentRoot,proto3" json:"commitment_root,omitempty"`
	UserDisclosureRoot []byte `protobuf:"bytes,7,opt,name=user_disclosure_root,json=userDisclosureRoot,proto3" json:"user_disclosure_root,omitempty"`
	FullDisclosureRoot []byte `protobuf:"bytes,8,opt,name=full_disclosure_root,json=fullDisclosureRoot,proto3" json:"full_disclosure_root,omitempty"`
	ExpiresAtUnix      int64  `protobuf:"varint,9,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
}

func (m *BatchMinimalEventWirePrototypeV1) Reset()         { *m = BatchMinimalEventWirePrototypeV1{} }
func (m *BatchMinimalEventWirePrototypeV1) String() string { return proto.CompactTextString(m) }
func (*BatchMinimalEventWirePrototypeV1) ProtoMessage()    {}
func (*BatchMinimalEventWirePrototypeV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce0974bff04c91f, []int{2}
}
func (m *BatchMinimalEventWirePrototypeV1) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BatchMinimalEventWirePrototypeV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BatchMinimalEventWirePrototypeV1.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BatchMinimalEventWirePrototypeV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchMinimalEventWirePrototypeV1.Merge(m, src)
}
func (m *BatchMinimalEventWirePrototypeV1) XXX_Size() int {
	return m.Size()
}
func (m *BatchMinimalEventWirePrototypeV1) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchMinimalEventWirePrototypeV1.DiscardUnknown(m)
}

var xxx_messageInfo_BatchMinimalEventWirePrototypeV1 proto.InternalMessageInfo

func (m *BatchMinimalEventWirePrototypeV1) GetEffectId() []byte {
	if m != nil {
		return m.EffectId
	}
	return nil
}

func (m *BatchMinimalEventWirePrototypeV1) GetRelayer() string {
	if m != nil {
		return m.Relayer
	}
	return ""
}

func (m *BatchMinimalEventWirePrototypeV1) GetInputCount() uint32 {
	if m != nil {
		return m.InputCount
	}
	return 0
}

func (m *BatchMinimalEventWirePrototypeV1) GetOutputCount() uint32 {
	if m != nil {
		return m.OutputCount
	}
	return 0
}

func (m *BatchMinimalEventWirePrototypeV1) GetNullifierRoot() []byte {
	if m != nil {
		return m.NullifierRoot
	}
	return nil
}

func (m *BatchMinimalEventWirePrototypeV1) GetCommitmentRoot() []byte {
	if m != nil {
		return m.CommitmentRoot
	}
	return nil
}

func (m *BatchMinimalEventWirePrototypeV1) GetUserDisclosureRoot() []byte {
	if m != nil {
		return m.UserDisclosureRoot
	}
	return nil
}

func (m *BatchMinimalEventWirePrototypeV1) GetFullDisclosureRoot() []byte {
	if m != nil {
		return m.FullDisclosureRoot
	}
	return nil
}

func (m *BatchMinimalEventWirePrototypeV1) GetExpiresAtUnix() int64 {
	if m != nil {
		return m.ExpiresAtUnix
	}
	return 0
}

func init() {
	proto.RegisterType((*BatchTransferWirePrototypeV1)(nil), "clairveil.privacy.v1.BatchTransferWirePrototypeV1")
	proto.RegisterType((*BatchTransferOutputWirePrototypeV1)(nil), "clairveil.privacy.v1.BatchTransferOutputWirePrototypeV1")
	proto.RegisterType((*BatchMinimalEventWirePrototypeV1)(nil), "clairveil.privacy.v1.BatchMinimalEventWirePrototypeV1")
}

func init() {
	proto.RegisterFile("clairveil/privacy/v1/batch_feasibility.proto", fileDescriptor_9ce0974bff04c91f)
}

var fileDescriptor_9ce0974bff04c91f = []byte{
	// 761 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcb, 0x6e, 0xdb, 0x38,
	0x14, 0x8d, 0x62, 0x3b, 0x8e, 0x69, 0x3b, 0xc1, 0x70, 0x3c, 0x19, 0xe5, 0xa5, 0xd1, 0x18, 0x98,
	0x19, 0x2d, 0xa6, 0x76, 0x9d, 0x16, 0x45, 0x76, 0x45, 0x5e, 0x68, 0x83, 0x24, 0xa8, 0xa1, 0x3a,
	0x29, 0x90, 0x8d, 0x20, 0x4b, 0x57, 0x36, 0x11, 0x59, 0x14, 0x28, 0xca, 0xb1, 0x3e, 0xa2, 0x40,
	0x3f, 0xab, 0xcb, 0x2c, 0xbb, 0x2c, 0x92, 0x75, 0x3f, 0xa0, 0xbb, 0x42, 0xa4, 0xdf, 0x36, 0xd0,
	0xee, 0xc4, 0x73, 0xcf, 0x21, 0xaf, 0x78, 0x0e, 0x2f, 0xfa, 0xdf, 0xf1, 0x6d, 0xc2, 0xfa, 0x40,
	0xfc, 0x7a, 0xc8, 0x48, 0xdf, 0x76, 0x92, 0x7a, 0xbf, 0x51, 0x6f, 0xdb, 0xdc, 0xe9, 0x5a, 0x1e,
	0xd8, 0x11, 0x69, 0x13, 0x9f, 0xf0, 0xa4, 0x16, 0x32, 0xca, 0x29, 0xae, 0x8c, 0xd9, 0xb5, 0x21,
	0xbb, 0xd6, 0x6f, 0xec, 0xec, 0x2f, 0xdd, 0x83, 0x0f, 0xa4, 0xa8, 0xfa, 0x31, 0x83, 0xf6, 0x8e,
	0xd3, 0x0d, 0x5b, 0xcc, 0x0e, 0x22, 0x0f, 0xd8, 0x07, 0xc2, 0xa0, 0x99, 0x96, 0x78, 0x12, 0xc2,
	0x4d, 0x03, 0xab, 0x28, 0xef, 0x30, 0xb0, 0x39, 0x65, 0xaa, 0xa2, 0x2b, 0x46, 0xc1, 0x1c, 0x2d,
	0x71, 0x05, 0xe5, 0x42, 0x46, 0xa9, 0xa7, 0xae, 0xea, 0x8a, 0x51, 0x32, 0xe5, 0x02, 0x63, 0x94,
	0x65, 0x94, 0x72, 0x35, 0x23, 0x40, 0xf1, 0x8d, 0x35, 0x84, 0x82, 0xd8, 0xf7, 0x89, 0x47, 0x80,
	0x45, 0x6a, 0x56, 0xcf, 0x18, 0x25, 0x73, 0x0a, 0xc1, 0x26, 0xca, 0xd3, 0x98, 0x87, 0x31, 0x8f,
	0xd4, 0x9c, 0x9e, 0x31, 0x8a, 0x07, 0x87, 0xb5, 0x65, 0xff, 0x52, 0x9b, 0x69, 0xf4, 0x9d, 0x50,
	0xcc, 0xb5, 0x6b, 0x8e, 0x36, 0xc2, 0x3a, 0x2a, 0xd9, 0xb1, 0x4b, 0xb8, 0x75, 0x07, 0x89, 0x45,
	0x5c, 0x75, 0x4d, 0x34, 0x8f, 0x04, 0x76, 0x01, 0xc9, 0xb9, 0x8b, 0xff, 0x45, 0x9b, 0x13, 0x06,
	0x84, 0xd4, 0xe9, 0xaa, 0x79, 0x5d, 0x31, 0xb2, 0x66, 0x79, 0x44, 0x3a, 0x4b, 0x41, 0x7c, 0x82,
	0x34, 0xc9, 0x73, 0x49, 0xe4, 0xf8, 0x34, 0x8a, 0x19, 0x58, 0xdc, 0x66, 0x1d, 0xe0, 0x56, 0x18,
	0xb7, 0xef, 0x20, 0x51, 0xd7, 0xc5, 0xbf, 0xee, 0x0a, 0xd6, 0xe9, 0x98, 0xd4, 0x12, 0x9c, 0xa6,
	0xa0, 0xa4, 0x87, 0xc1, 0x20, 0x24, 0x0c, 0x22, 0xcb, 0xe6, 0x56, 0x1c, 0x90, 0x81, 0x5a, 0xd0,
	0x15, 0x23, 0x63, 0x96, 0x87, 0xf0, 0x11, 0xbf, 0x0e, 0xc8, 0xa0, 0xfa, 0x2d, 0x8b, 0xaa, 0x3f,
	0xff, 0xcd, 0xf4, 0x46, 0x1d, 0xda, 0xeb, 0x11, 0xde, 0x83, 0x80, 0x0b, 0x63, 0x4a, 0xe6, 0x14,
	0x22, 0xea, 0x24, 0xec, 0x02, 0xe3, 0x30, 0xe0, 0x43, 0x83, 0xa6, 0x10, 0xbc, 0x8d, 0xd6, 0xfb,
	0x04, 0xee, 0x2d, 0x6e, 0x77, 0x86, 0x4e, 0xe5, 0xd3, 0x75, 0xcb, 0xee, 0xe0, 0x1a, 0xfa, 0x3d,
	0x8e, 0x80, 0x59, 0xc3, 0x7b, 0xb7, 0x42, 0xea, 0x13, 0x27, 0x51, 0xb3, 0xba, 0x62, 0x94, 0xcd,
	0xdf, 0xd2, 0x52, 0x53, 0x56, 0x9a, 0xa2, 0x80, 0x6f, 0x51, 0x45, 0xf0, 0xa7, 0x6e, 0xa7, 0x47,
	0x5d, 0x50, 0x73, 0xba, 0x62, 0x6c, 0x1c, 0x18, 0xcb, 0x9d, 0xbc, 0x8e, 0x80, 0x4d, 0x6e, 0xea,
	0x8a, 0xba, 0x60, 0xe2, 0x78, 0x01, 0xc3, 0x2f, 0xd1, 0xd6, 0xfc, 0xde, 0x2e, 0xe9, 0x40, 0xc4,
	0x85, 0x9d, 0x25, 0xb3, 0x32, 0xab, 0x39, 0x15, 0x35, 0x7c, 0x84, 0xf6, 0xe7, 0x55, 0xb3, 0x7e,
	0xe5, 0x85, 0x78, 0x67, 0x56, 0x3c, 0x63, 0xd7, 0x2b, 0xf4, 0xe7, 0xfc, 0x16, 0xa1, 0x9d, 0xf8,
	0xd4, 0x76, 0x87, 0x66, 0xff, 0x31, 0x2b, 0x6e, 0xca, 0x62, 0xda, 0xb0, 0x17, 0xfb, 0xfe, 0x92,
	0x86, 0x0b, 0xb2, 0xe1, 0xb4, 0xba, 0xd0, 0xf0, 0x21, 0x52, 0x17, 0x12, 0x36, 0x3a, 0x0e, 0x09,
	0xdd, 0xd6, 0x5c, 0xb6, 0x46, 0xe7, 0xbd, 0x46, 0x7b, 0x11, 0xf8, 0x9e, 0x25, 0xcc, 0x5c, 0xa2,
	0x2e, 0x0a, 0xf5, 0x76, 0xca, 0xb9, 0x21, 0x70, 0xbf, 0xb0, 0x41, 0xf5, 0xfb, 0x2a, 0xd2, 0x45,
	0xde, 0xae, 0x48, 0x40, 0x7a, 0xb6, 0x7f, 0xd6, 0x87, 0x60, 0x21, 0x6d, 0xbb, 0xa8, 0x00, 0x9e,
	0x07, 0x0e, 0x4f, 0x1f, 0x92, 0x0c, 0xdb, 0xba, 0x04, 0xce, 0xdd, 0x74, 0x40, 0x30, 0xf0, 0xed,
	0x04, 0x98, 0xc8, 0x59, 0xc1, 0x1c, 0x2d, 0xf1, 0x5f, 0xa8, 0x48, 0x82, 0x30, 0xe6, 0x96, 0x43,
	0xe3, 0x40, 0x4e, 0x84, 0xb2, 0x89, 0x04, 0x74, 0x92, 0x22, 0xf8, 0x6f, 0x54, 0x92, 0xcf, 0x75,
	0xc8, 0x90, 0x19, 0x2b, 0x4a, 0x4c, 0x52, 0xfe, 0x41, 0x1b, 0xe3, 0x41, 0x61, 0x89, 0xc1, 0x92,
	0x13, 0xe7, 0x97, 0xc7, 0xa8, 0x99, 0x4e, 0x98, 0xff, 0xd0, 0xe6, 0x24, 0xfd, 0x92, 0x27, 0x13,
	0xb2, 0x31, 0x81, 0x05, 0xf1, 0xf9, 0x62, 0x5a, 0x05, 0x5b, 0x46, 0x62, 0x2e, 0x83, 0x23, 0xc5,
	0xbc, 0xa5, 0x42, 0x21, 0x73, 0x80, 0x67, 0x0d, 0x15, 0x8a, 0x5f, 0x7c, 0xeb, 0xc7, 0x17, 0x9f,
	0x1f, 0x35, 0xe5, 0xe1, 0x51, 0x53, 0xbe, 0x3e, 0x6a, 0xca, 0xa7, 0x27, 0x6d, 0xe5, 0xe1, 0x49,
	0x5b, 0xf9, 0xf2, 0xa4, 0xad, 0xdc, 0x36, 0x3a, 0x84, 0x77, 0xe3, 0x76, 0xcd, 0xa1, 0xbd, 0xfa,
	0xe9, 0xd9, 0xe5, 0xf9, 0x9b, 0xb7, 0xad, 0x67, 0x97, 0x47, 0xc7, 0xef, 0xeb, 0x93, 0x61, 0x3e,
	0x18, 0x8f, 0xf3, 0xd4, 0xa4, 0xa8, 0xbd, 0x26, 0xe6, 0xf9, 0x8b, 0x1f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xcc, 0x75, 0xb1, 0xab, 0x34, 0x06, 0x00, 0x00,
}

func (m *BatchTransferWirePrototypeV1) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BatchTransferWirePrototypeV1) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BatchTransferWirePrototypeV1) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExpiresAtUnix != 0 {
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(m.ExpiresAtUnix))
		i--
		dAtA[i] = 0x48
	}
	if len(m.AuditDisclosureTargetPubkey) > 0 {
		i -= len(m.AuditDisclosureTargetPubkey)
		copy(dAtA[i:], m.AuditDisclosureTargetPubkey)
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(len(m.AuditDisclosureTargetPubkey)))
		i--
		dAtA[i] = 0x42
	}
	if m.AuditKeyEpoch != 0 {
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(m.AuditKeyEpoch))
		i--
		dAtA[i] = 0x38
	}
	if len(m.AuditKeyId) > 0 {
		i -= len(m.AuditKeyId)
		copy(dAtA[i:], m.AuditKeyId)
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(len(m.AuditKeyId)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Outputs) > 0 {
		for iNdEx := len(m.Outputs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Outputs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintBatchFeasibility(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Nullifiers) > 0 {
		for iNdEx := len(m.Nullifiers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Nullifiers[iNdEx])
			copy(dAtA[i:], m.Nullifiers[iNdEx])
			i = encodeVarintBatchFeasibility(dAtA, i, uint64(len(m.Nullifiers[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Root) > 0 {
		i -= len(m.Root)
		copy(dAtA[i:], m.Root)
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(len(m.Root)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Proof) > 0 {
		i -= len(m.Proof)
		copy(dAtA[i:], m.Proof)
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(len(m.Proof)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *BatchTransferOutputWirePrototypeV1) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BatchTransferOutputWirePrototypeV1) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BatchTransferOutputWirePrototypeV1) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SelfViewDisclosurePayload) > 0 {
		i -= len(m.SelfViewDisclosurePayload)
		copy(dAtA[i:], m.SelfViewDisclosurePayload)
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(len(m.SelfViewDisclosurePayload)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.AuditDisclosurePayload) > 0 {
		i -= len(m.AuditDisclosurePayload)
		copy(dAtA[i:], m.AuditDisclosurePayload)
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(len(m.AuditDisclosurePayload)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.FullDisclosureDigest) > 0 {
		i -= len(m.FullDisclosureDigest)
		copy(dAtA[i:], m.FullDisclosureDigest)
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(len(m.FullDisclosureDigest)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.UserDisclosurePayload) > 0 {
		i -= len(m.UserDisclosurePayload)
		copy(dAtA[i:], m.UserDisclosurePayload)
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(len(m.UserDisclosurePayload)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.UserDisclosureTargetPubkey) > 0 {
		i -= len(m.UserDisclosureTargetPubkey)
		copy(dAtA[i:], m.UserDisclosureTargetPubkey)
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(len(m.UserDisclosureTargetPubkey)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.UserDisclosureDigest) > 0 {
		i -= len(m.UserDisclosureDigest)
		copy(dAtA[i:], m.UserDisclosureDigest)
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(len(m.UserDisclosureDigest)))
		i--
		dAtA[i] = 0x32
	}
	if m.UserDisclosureMode != 0 {
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(m.UserDisclosureMode))
		i--
		dAtA[i] = 0x28
	}
	if m.UserPrivacyPolicy != 0 {
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(m.UserPrivacyPolicy))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ViewTag) > 0 {
		i -= len(m.ViewTag)
		copy(dAtA[i:], m.ViewTag)
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(len(m.ViewTag)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Ciphertext) > 0 {
		i -= len(m.Ciphertext)
		copy(dAtA[i:], m.Ciphertext)
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(len(m.Ciphertext)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Commitment) > 0 {
		i -= len(m.Commitment)
		copy(dAtA[i:], m.Commitment)
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(len(m.Commitment)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *BatchMinimalEventWirePrototypeV1) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BatchMinimalEventWirePrototypeV1) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BatchMinimalEventWirePrototypeV1) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExpiresAtUnix != 0 {
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(m.ExpiresAtUnix))
		i--
		dAtA[i] = 0x48
	}
	if len(m.FullDisclosureRoot) > 0 {
		i -= len(m.FullDisclosureRoot)
		copy(dAtA[i:], m.FullDisclosureRoot)
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(len(m.FullDisclosureRoot)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.UserDisclosureRoot) > 0 {
		i -= len(m.UserDisclosureRoot)
		copy(dAtA[i:], m.UserDisclosureRoot)
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(len(m.UserDisclosureRoot)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.CommitmentRoot) > 0 {
		i -= len(m.CommitmentRoot)
		copy(dAtA[i:], m.CommitmentRoot)
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(len(m.CommitmentRoot)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.NullifierRoot) > 0 {
		i -= len(m.NullifierRoot)
		copy(dAtA[i:], m.NullifierRoot)
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(len(m.NullifierRoot)))
		i--
		dAtA[i] = 0x2a
	}
	if m.OutputCount != 0 {
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(m.OutputCount))
		i--
		dAtA[i] = 0x20
	}
	if m.InputCount != 0 {
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(m.InputCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Relayer) > 0 {
		i -= len(m.Relayer)
		copy(dAtA[i:], m.Relayer)
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(len(m.Relayer)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.EffectId) > 0 {
		i -= len(m.EffectId)
		copy(dAtA[i:], m.EffectId)
		i = encodeVarintBatchFeasibility(dAtA, i, uint64(len(m.EffectId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintBatchFeasibility(dAtA []byte, offset int, v uint64) int {
	offset -= sovBatchFeasibility(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BatchTransferWirePrototypeV1) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovBatchFeasibility(uint64(l))
	}
	l = len(m.Proof)
	if l > 0 {
		n += 1 + l + sovBatchFeasibility(uint64(l))
	}
	l = len(m.Root)
	if l > 0 {
		n += 1 + l + sovBatchFeasibility(uint64(l))
	}
	if len(m.Nullifiers) > 0 {
		for _, b := range m.Nullifiers {
			l = len(b)
			n += 1 + l + sovBatchFeasibility(uint64(l))
		}
	}
	if len(m.Outputs) > 0 {
		for _, e := range m.Outputs {
			l = e.Size()
			n += 1 + l + sovBatchFeasibility(uint64(l))
		}
	}
	l = len(m.AuditKeyId)
	if l > 0 {
		n += 1 + l + sovBatchFeasibility(uint64(l))
	}
	if m.AuditKeyEpoch != 0 {
		n += 1 + sovBatchFeasibility(uint64(m.AuditKeyEpoch))
	}
	l = len(m.AuditDisclosureTargetPubkey)
	if l > 0 {
		n += 1 + l + sovBatchFeasibility(uint64(l))
	}
	if m.ExpiresAtUnix != 0 {
		n += 1 + sovBatchFeasibility(uint64(m.ExpiresAtUnix))
	}
	return n
}

func (m *BatchTransferOutputWirePrototypeV1) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Commitment)
	if l > 0 {
		n += 1 + l + sovBatchFeasibility(uint64(l))
	}
	l = len(m.Ciphertext)
	if l > 0 {
		n += 1 + l + sovBatchFeasibility(uint64(l))
	}
	l = len(m.ViewTag)
	if l > 0 {
		n += 1 + l + sovBatchFeasibility(uint64(l))
	}
	if m.UserPrivacyPolicy != 0 {
		n += 1 + sovBatchFeasibility(uint64(m.UserPrivacyPolicy))
	}
	if m.UserDisclosureMode != 0 {
		n += 1 + sovBatchFeasibility(uint64(m.UserDisclosureMode))
	}
	l = len(m.UserDisclosureDigest)
	if l > 0 {
		n += 1 + l + sovBatchFeasibility(uint64(l))
	}
	l = len(m.UserDisclosureTargetPubkey)
	if l > 0 {
		n += 1 + l + sovBatchFeasibility(uint64(l))
	}
	l = len(m.UserDisclosurePayload)
	if l > 0 {
		n += 1 + l + sovBatchFeasibility(uint64(l))
	}
	l = len(m.FullDisclosureDigest)
	if l > 0 {
		n += 1 + l + sovBatchFeasibility(uint64(l))
	}
	l = len(m.AuditDisclosurePayload)
	if l > 0 {
		n += 1 + l + sovBatchFeasibility(uint64(l))
	}
	l = len(m.SelfViewDisclosurePayload)
	if l > 0 {
		n += 1 + l + sovBatchFeasibility(uint64(l))
	}
	return n
}

func (m *BatchMinimalEventWirePrototypeV1) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EffectId)
	if l > 0 {
		n += 1 + l + sovBatchFeasibility(uint64(l))
	}
	l = len(m.Relayer)
	if l > 0 {
		n += 1 + l + sovBatchFeasibility(uint64(l))
	}
	if m.InputCount != 0 {
		n += 1 + sovBatchFeasibility(uint64(m.InputCount))
	}
	if m.OutputCount != 0 {
		n += 1 + sovBatchFeasibility(uint64(m.OutputCount))
	}
	l = len(m.NullifierRoot)
	if l > 0 {
		n += 1 + l + sovBatchFeasibility(uint64(l))
	}
	l = len(m.CommitmentRoot)
	if l > 0 {
		n += 1 + l + sovBatchFeasibility(uint64(l))
	}
	l = len(m.UserDisclosureRoot)
	if l > 0 {
		n += 1 + l + sovBatchFeasibility(uint64(l))
	}
	l = len(m.FullDisclosureRoot)
	if l > 0 {
		n += 1 + l + sovBatchFeasibility(uint64(l))
	}
	if m.ExpiresAtUnix != 0 {
		n += 1 + sovBatchFeasibility(uint64(m.ExpiresAtUnix))
	}
	return n
}

func sovBatchFeasibility(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBatchFeasibility(x uint64) (n int) {
	return sovBatchFeasibility(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BatchTransferWirePrototypeV1) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBatchFeasibility
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BatchTransferWirePrototypeV1: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BatchTransferWirePrototypeV1: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = append(m.Proof[:0], dAtA[iNdEx:postIndex]...)
			if m.Proof == nil {
				m.Proof = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Root = append(m.Root[:0], dAtA[iNdEx:postIndex]...)
			if m.Root == nil {
				m.Root = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nullifiers", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nullifiers = append(m.Nullifiers, make([]byte, postIndex-iNdEx))
			copy(m.Nullifiers[len(m.Nullifiers)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Outputs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Outputs = append(m.Outputs, &BatchTransferOutputWirePrototypeV1{})
			if err := m.Outputs[len(m.Outputs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditKeyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuditKeyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditKeyEpoch", wireType)
			}
			m.AuditKeyEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuditKeyEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditDisclosureTargetPubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuditDisclosureTargetPubkey = append(m.AuditDisclosureTargetPubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.AuditDisclosureTargetPubkey == nil {
				m.AuditDisclosureTargetPubkey = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAtUnix", wireType)
			}
			m.ExpiresAtUnix = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiresAtUnix |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBatchFeasibility(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BatchTransferOutputWirePrototypeV1) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBatchFeasibility
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BatchTransferOutputWirePrototypeV1: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BatchTransferOutputWirePrototypeV1: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Commitment = append(m.Commitment[:0], dAtA[iNdEx:postIndex]...)
			if m.Commitment == nil {
				m.Commitment = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ciphertext", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ciphertext = append(m.Ciphertext[:0], dAtA[iNdEx:postIndex]...)
			if m.Ciphertext == nil {
				m.Ciphertext = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ViewTag", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ViewTag = append(m.ViewTag[:0], dAtA[iNdEx:postIndex]...)
			if m.ViewTag == nil {
				m.ViewTag = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserPrivacyPolicy", wireType)
			}
			m.UserPrivacyPolicy = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserPrivacyPolicy |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserDisclosureMode", wireType)
			}
			m.UserDisclosureMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserDisclosureMode |= UserDisclosureMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserDisclosureDigest", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserDisclosureDigest = append(m.UserDisclosureDigest[:0], dAtA[iNdEx:postIndex]...)
			if m.UserDisclosureDigest == nil {
				m.UserDisclosureDigest = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserDisclosureTargetPubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserDisclosureTargetPubkey = append(m.UserDisclosureTargetPubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.UserDisclosureTargetPubkey == nil {
				m.UserDisclosureTargetPubkey = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserDisclosurePayload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserDisclosurePayload = append(m.UserDisclosurePayload[:0], dAtA[iNdEx:postIndex]...)
			if m.UserDisclosurePayload == nil {
				m.UserDisclosurePayload = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FullDisclosureDigest", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FullDisclosureDigest = append(m.FullDisclosureDigest[:0], dAtA[iNdEx:postIndex]...)
			if m.FullDisclosureDigest == nil {
				m.FullDisclosureDigest = []byte{}
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditDisclosurePayload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuditDisclosurePayload = append(m.AuditDisclosurePayload[:0], dAtA[iNdEx:postIndex]...)
			if m.AuditDisclosurePayload == nil {
				m.AuditDisclosurePayload = []byte{}
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SelfViewDisclosurePayload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SelfViewDisclosurePayload = append(m.SelfViewDisclosurePayload[:0], dAtA[iNdEx:postIndex]...)
			if m.SelfViewDisclosurePayload == nil {
				m.SelfViewDisclosurePayload = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBatchFeasibility(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BatchMinimalEventWirePrototypeV1) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBatchFeasibility
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BatchMinimalEventWirePrototypeV1: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BatchMinimalEventWirePrototypeV1: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EffectId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EffectId = append(m.EffectId[:0], dAtA[iNdEx:postIndex]...)
			if m.EffectId == nil {
				m.EffectId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Relayer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Relayer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InputCount", wireType)
			}
			m.InputCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InputCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutputCount", wireType)
			}
			m.OutputCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OutputCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NullifierRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NullifierRoot = append(m.NullifierRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.NullifierRoot == nil {
				m.NullifierRoot = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitmentRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommitmentRoot = append(m.CommitmentRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.CommitmentRoot == nil {
				m.CommitmentRoot = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserDisclosureRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserDisclosureRoot = append(m.UserDisclosureRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.UserDisclosureRoot == nil {
				m.UserDisclosureRoot = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FullDisclosureRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FullDisclosureRoot = append(m.FullDisclosureRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.FullDisclosureRoot == nil {
				m.FullDisclosureRoot = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAtUnix", wireType)
			}
			m.ExpiresAtUnix = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiresAtUnix |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBatchFeasibility(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBatchFeasibility
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBatchFeasibility(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBatchFeasibility
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBatchFeasibility
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBatchFeasibility
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBatchFeasibility
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBatchFeasibility
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBatchFeasibility        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBatchFeasibility          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBatchFeasibility = fmt.Errorf("proto: unexpected end of group")
)
