// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: clairveil/privacy/v1/genesis.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the bank module's genesis state.
type GenesisState struct {
	Commitments       [][]byte `protobuf:"bytes,1,rep,name=commitments,proto3" json:"commitments,omitempty"`
	HistoricalRoots   [][]byte `protobuf:"bytes,2,rep,name=historical_roots,json=historicalRoots,proto3" json:"historical_roots,omitempty"`
	Nullifiers        [][]byte `protobuf:"bytes,3,rep,name=nullifiers,proto3" json:"nullifiers,omitempty"`
	AuditMasterPubkey []byte   `protobuf:"bytes,4,opt,name=audit_master_pubkey,json=auditMasterPubkey,proto3" json:"audit_master_pubkey,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6c50cde138729b1, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetCommitments() [][]byte {
	if m != nil {
		return m.Commitments
	}
	return nil
}

func (m *GenesisState) GetHistoricalRoots() [][]byte {
	if m != nil {
		return m.HistoricalRoots
	}
	return nil
}

func (m *GenesisState) GetNullifiers() [][]byte {
	if m != nil {
		return m.Nullifiers
	}
	return nil
}

func (m *GenesisState) GetAuditMasterPubkey() []byte {
	if m != nil {
		return m.AuditMasterPubkey
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "clairveil.privacy.v1.GenesisState")
}

func init() {
	proto.RegisterFile("clairveil/privacy/v1/genesis.proto", fileDescriptor_c6c50cde138729b1)
}

var fileDescriptor_c6c50cde138729b1 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x31, 0x4e, 0xf3, 0x30,
	0x18, 0x40, 0xe3, 0xbf, 0xbf, 0x18, 0x4c, 0x24, 0x20, 0x30, 0x64, 0xb2, 0xa2, 0x4e, 0x65, 0x20,
	0x51, 0xc4, 0x09, 0xa8, 0x40, 0x05, 0x51, 0x24, 0x94, 0x32, 0xb1, 0x44, 0x4e, 0x30, 0xed, 0x27,
	0xec, 0x38, 0xb2, 0xbf, 0x44, 0xe4, 0x16, 0xdc, 0x83, 0x8b, 0x30, 0x76, 0x64, 0x44, 0xc9, 0x45,
	0x10, 0x06, 0xb5, 0x5d, 0xdf, 0x7b, 0xd3, 0xa3, 0xe3, 0x52, 0x72, 0x30, 0xad, 0x00, 0x99, 0xd4,
	0x06, 0x5a, 0x5e, 0x76, 0x49, 0x9b, 0x26, 0x4b, 0x51, 0x09, 0x0b, 0x36, 0xae, 0x8d, 0x46, 0x1d,
	0x9c, 0x6c, 0x9a, 0xf8, 0xaf, 0x89, 0xdb, 0x74, 0xfc, 0x4e, 0xa8, 0x3f, 0xfb, 0xed, 0x16, 0xc8,
	0x51, 0x04, 0x11, 0xdd, 0x2f, 0xb5, 0x52, 0x80, 0x4a, 0x54, 0x68, 0x43, 0x12, 0x8d, 0x26, 0x7e,
	0xb6, 0x8b, 0x82, 0x53, 0x7a, 0xb8, 0x02, 0x8b, 0xda, 0x40, 0xc9, 0x65, 0x6e, 0xb4, 0x46, 0x1b,
	0xfe, 0x73, 0xd9, 0xc1, 0x96, 0x67, 0x3f, 0x38, 0x60, 0x94, 0x56, 0x8d, 0x94, 0xf0, 0x0c, 0xc2,
	0xd8, 0x70, 0xe4, 0xa2, 0x1d, 0x12, 0xc4, 0xf4, 0x98, 0x37, 0x4f, 0x80, 0xb9, 0xe2, 0x16, 0x85,
	0xc9, 0xeb, 0xa6, 0x78, 0x11, 0x5d, 0xf8, 0x3f, 0x22, 0x13, 0x3f, 0x3b, 0x72, 0xea, 0xce, 0x99,
	0x7b, 0x27, 0xa6, 0xb7, 0x1f, 0x3d, 0x23, 0xeb, 0x9e, 0x91, 0xaf, 0x9e, 0x91, 0xb7, 0x81, 0x79,
	0xeb, 0x81, 0x79, 0x9f, 0x03, 0xf3, 0x1e, 0xd3, 0x25, 0xe0, 0xaa, 0x29, 0xe2, 0x52, 0xab, 0xe4,
	0xf2, 0x6a, 0x7e, 0x33, 0xbb, 0x7e, 0x38, 0x9b, 0x5f, 0x4c, 0x17, 0xc9, 0xf6, 0xcc, 0xeb, 0xe6,
	0x0d, 0x76, 0xb5, 0xb0, 0xc5, 0x9e, 0xfb, 0x72, 0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x4a, 0xd9,
	0xee, 0x2f, 0x3d, 0x01, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AuditMasterPubkey) > 0 {
		i -= len(m.AuditMasterPubkey)
		copy(dAtA[i:], m.AuditMasterPubkey)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.AuditMasterPubkey)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Nullifiers) > 0 {
		for iNdEx := len(m.Nullifiers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Nullifiers[iNdEx])
			copy(dAtA[i:], m.Nullifiers[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.Nullifiers[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.HistoricalRoots) > 0 {
		for iNdEx := len(m.HistoricalRoots) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.HistoricalRoots[iNdEx])
			copy(dAtA[i:], m.HistoricalRoots[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.HistoricalRoots[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Commitments) > 0 {
		for iNdEx := len(m.Commitments) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Commitments[iNdEx])
			copy(dAtA[i:], m.Commitments[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.Commitments[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Commitments) > 0 {
		for _, b := range m.Commitments {
			l = len(b)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.HistoricalRoots) > 0 {
		for _, b := range m.HistoricalRoots {
			l = len(b)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Nullifiers) > 0 {
		for _, b := range m.Nullifiers {
			l = len(b)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = len(m.AuditMasterPubkey)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commitments", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Commitments = append(m.Commitments, make([]byte, postIndex-iNdEx))
			copy(m.Commitments[len(m.Commitments)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HistoricalRoots", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HistoricalRoots = append(m.HistoricalRoots, make([]byte, postIndex-iNdEx))
			copy(m.HistoricalRoots[len(m.HistoricalRoots)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nullifiers", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nullifiers = append(m.Nullifiers, make([]byte, postIndex-iNdEx))
			copy(m.Nullifiers[len(m.Nullifiers)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditMasterPubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuditMasterPubkey = append(m.AuditMasterPubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.AuditMasterPubkey == nil {
				m.AuditMasterPubkey = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
