// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: clairveil/privacy/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type UserDisclosureMode int32

const (
	UserDisclosureMode_USER_DISCLOSURE_MODE_NONE                UserDisclosureMode = 0
	UserDisclosureMode_USER_DISCLOSURE_MODE_PUBLIC              UserDisclosureMode = 1
	UserDisclosureMode_USER_DISCLOSURE_MODE_RECIPIENT_ENCRYPTED UserDisclosureMode = 2
)

var UserDisclosureMode_name = map[int32]string{
	0: "USER_DISCLOSURE_MODE_NONE",
	1: "USER_DISCLOSURE_MODE_PUBLIC",
	2: "USER_DISCLOSURE_MODE_RECIPIENT_ENCRYPTED",
}

var UserDisclosureMode_value = map[string]int32{
	"USER_DISCLOSURE_MODE_NONE":                0,
	"USER_DISCLOSURE_MODE_PUBLIC":              1,
	"USER_DISCLOSURE_MODE_RECIPIENT_ENCRYPTED": 2,
}

func (x UserDisclosureMode) String() string {
	return proto.EnumName(UserDisclosureMode_name, int32(x))
}

func (UserDisclosureMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cbddc2210f6432c2, []int{0}
}

// MsgDeposit: 투명 자산 -> 익명 자산 변환
type MsgDeposit struct {
	Creator        string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Amount         string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	NoteCommitment []byte `protobuf:"bytes,3,opt,name=note_commitment,json=noteCommitment,proto3" json:"note_commitment,omitempty"`
	EncryptedNote  []byte `protobuf:"bytes,4,opt,name=encrypted_note,json=encryptedNote,proto3" json:"encrypted_note,omitempty"`
}

func (m *MsgDeposit) Reset()         { *m = MsgDeposit{} }
func (m *MsgDeposit) String() string { return proto.CompactTextString(m) }
func (*MsgDeposit) ProtoMessage()    {}
func (*MsgDeposit) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbddc2210f6432c2, []int{0}
}
func (m *MsgDeposit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeposit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeposit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeposit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeposit.Merge(m, src)
}
func (m *MsgDeposit) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeposit) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeposit.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeposit proto.InternalMessageInfo

func (m *MsgDeposit) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeposit) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *MsgDeposit) GetNoteCommitment() []byte {
	if m != nil {
		return m.NoteCommitment
	}
	return nil
}

func (m *MsgDeposit) GetEncryptedNote() []byte {
	if m != nil {
		return m.EncryptedNote
	}
	return nil
}

// MsgWithdraw: 익명 자산 -> 투명 자산 변환 (Input Note -> Output Note)
type MsgWithdraw struct {
	Creator           string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Proof             []byte `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	Root              []byte `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	Nullifier         []byte `protobuf:"bytes,4,opt,name=nullifier,proto3" json:"nullifier,omitempty"`
	NewNoteCommitment []byte `protobuf:"bytes,5,opt,name=new_note_commitment,json=newNoteCommitment,proto3" json:"new_note_commitment,omitempty"`
	EncryptedNote     []byte `protobuf:"bytes,6,opt,name=encrypted_note,json=encryptedNote,proto3" json:"encrypted_note,omitempty"`
	Amount            string `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Recipient         string `protobuf:"bytes,8,opt,name=recipient,proto3" json:"recipient,omitempty"`
	ChainId           string `protobuf:"bytes,9,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ExpiresAtUnix     int64  `protobuf:"varint,10,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
}

func (m *MsgWithdraw) Reset()         { *m = MsgWithdraw{} }
func (m *MsgWithdraw) String() string { return proto.CompactTextString(m) }
func (*MsgWithdraw) ProtoMessage()    {}
func (*MsgWithdraw) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbddc2210f6432c2, []int{1}
}
func (m *MsgWithdraw) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdraw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdraw.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdraw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdraw.Merge(m, src)
}
func (m *MsgWithdraw) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdraw) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdraw.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdraw proto.InternalMessageInfo

func (m *MsgWithdraw) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgWithdraw) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *MsgWithdraw) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *MsgWithdraw) GetNullifier() []byte {
	if m != nil {
		return m.Nullifier
	}
	return nil
}

func (m *MsgWithdraw) GetNewNoteCommitment() []byte {
	if m != nil {
		return m.NewNoteCommitment
	}
	return nil
}

func (m *MsgWithdraw) GetEncryptedNote() []byte {
	if m != nil {
		return m.EncryptedNote
	}
	return nil
}

func (m *MsgWithdraw) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *MsgWithdraw) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *MsgWithdraw) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *MsgWithdraw) GetExpiresAtUnix() int64 {
	if m != nil {
		return m.ExpiresAtUnix
	}
	return 0
}

// MsgTransfer: 내부 전송
type MsgTransfer struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	// ZK Proof Data
	Proof      []byte   `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	Root       []byte   `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	Nullifiers [][]byte `protobuf:"bytes,4,rep,name=nullifiers,proto3" json:"nullifiers,omitempty"`
	// Output Commitments (Recipient, Change)
	NewCommitments [][]byte `protobuf:"bytes,5,rep,name=new_commitments,json=newCommitments,proto3" json:"new_commitments,omitempty"`
	// On-chain Encryption (ECDH Encrypted Data)
	// 수신자가 복호화해서 Note 정보를 알 수 있게 함
	CipherTexts [][]byte `protobuf:"bytes,6,rep,name=cipher_texts,json=cipherTexts,proto3" json:"cipher_texts,omitempty"`
	// Optional user selective disclosure.
	// 0x00: all-private
	// 0x01: disclose amount (+ asset id)
	// 0x02: disclose recipient full shielded address
	// 0x04: disclose sender full shielded address
	UserPrivacyPolicy          uint32             `protobuf:"varint,7,opt,name=user_privacy_policy,json=userPrivacyPolicy,proto3" json:"user_privacy_policy,omitempty"`
	UserDisclosureDigest       []byte             `protobuf:"bytes,8,opt,name=user_disclosure_digest,json=userDisclosureDigest,proto3" json:"user_disclosure_digest,omitempty"`
	UserDisclosureMode         UserDisclosureMode `protobuf:"varint,9,opt,name=user_disclosure_mode,json=userDisclosureMode,proto3,enum=clairveil.privacy.v1.UserDisclosureMode" json:"user_disclosure_mode,omitempty"`
	UserDisclosureTargetPubkey []byte             `protobuf:"bytes,10,opt,name=user_disclosure_target_pubkey,json=userDisclosureTargetPubkey,proto3" json:"user_disclosure_target_pubkey,omitempty"`
	UserDisclosurePayload      []byte             `protobuf:"bytes,11,opt,name=user_disclosure_payload,json=userDisclosurePayload,proto3" json:"user_disclosure_payload,omitempty"`
	// Mandatory master-auditor disclosure.
	AuditDisclosureDigest       []byte `protobuf:"bytes,12,opt,name=audit_disclosure_digest,json=auditDisclosureDigest,proto3" json:"audit_disclosure_digest,omitempty"`
	AuditDisclosureTargetPubkey []byte `protobuf:"bytes,13,opt,name=audit_disclosure_target_pubkey,json=auditDisclosureTargetPubkey,proto3" json:"audit_disclosure_target_pubkey,omitempty"`
	AuditDisclosurePayload      []byte `protobuf:"bytes,14,opt,name=audit_disclosure_payload,json=auditDisclosurePayload,proto3" json:"audit_disclosure_payload,omitempty"`
}

func (m *MsgTransfer) Reset()         { *m = MsgTransfer{} }
func (m *MsgTransfer) String() string { return proto.CompactTextString(m) }
func (*MsgTransfer) ProtoMessage()    {}
func (*MsgTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbddc2210f6432c2, []int{2}
}
func (m *MsgTransfer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransfer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransfer.Merge(m, src)
}
func (m *MsgTransfer) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransfer proto.InternalMessageInfo

func (m *MsgTransfer) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgTransfer) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *MsgTransfer) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *MsgTransfer) GetNullifiers() [][]byte {
	if m != nil {
		return m.Nullifiers
	}
	return nil
}

func (m *MsgTransfer) GetNewCommitments() [][]byte {
	if m != nil {
		return m.NewCommitments
	}
	return nil
}

func (m *MsgTransfer) GetCipherTexts() [][]byte {
	if m != nil {
		return m.CipherTexts
	}
	return nil
}

func (m *MsgTransfer) GetUserPrivacyPolicy() uint32 {
	if m != nil {
		return m.UserPrivacyPolicy
	}
	return 0
}

func (m *MsgTransfer) GetUserDisclosureDigest() []byte {
	if m != nil {
		return m.UserDisclosureDigest
	}
	return nil
}

func (m *MsgTransfer) GetUserDisclosureMode() UserDisclosureMode {
	if m != nil {
		return m.UserDisclosureMode
	}
	return UserDisclosureMode_USER_DISCLOSURE_MODE_NONE
}

func (m *MsgTransfer) GetUserDisclosureTargetPubkey() []byte {
	if m != nil {
		return m.UserDisclosureTargetPubkey
	}
	return nil
}

func (m *MsgTransfer) GetUserDisclosurePayload() []byte {
	if m != nil {
		return m.UserDisclosurePayload
	}
	return nil
}

func (m *MsgTransfer) GetAuditDisclosureDigest() []byte {
	if m != nil {
		return m.AuditDisclosureDigest
	}
	return nil
}

func (m *MsgTransfer) GetAuditDisclosureTargetPubkey() []byte {
	if m != nil {
		return m.AuditDisclosureTargetPubkey
	}
	return nil
}

func (m *MsgTransfer) GetAuditDisclosurePayload() []byte {
	if m != nil {
		return m.AuditDisclosurePayload
	}
	return nil
}

// MsgDepositResponse
type MsgDepositResponse struct {
}

func (m *MsgDepositResponse) Reset()         { *m = MsgDepositResponse{} }
func (m *MsgDepositResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDepositResponse) ProtoMessage()    {}
func (*MsgDepositResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbddc2210f6432c2, []int{3}
}
func (m *MsgDepositResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDepositResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDepositResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDepositResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDepositResponse.Merge(m, src)
}
func (m *MsgDepositResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDepositResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDepositResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDepositResponse proto.InternalMessageInfo

// MsgWithdrawResponse
type MsgWithdrawResponse struct {
}

func (m *MsgWithdrawResponse) Reset()         { *m = MsgWithdrawResponse{} }
func (m *MsgWithdrawResponse) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawResponse) ProtoMessage()    {}
func (*MsgWithdrawResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbddc2210f6432c2, []int{4}
}
func (m *MsgWithdrawResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawResponse.Merge(m, src)
}
func (m *MsgWithdrawResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawResponse proto.InternalMessageInfo

// MsgTransferResponse
type MsgTransferResponse struct {
}

func (m *MsgTransferResponse) Reset()         { *m = MsgTransferResponse{} }
func (m *MsgTransferResponse) String() string { return proto.CompactTextString(m) }
func (*MsgTransferResponse) ProtoMessage()    {}
func (*MsgTransferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbddc2210f6432c2, []int{5}
}
func (m *MsgTransferResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransferResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferResponse.Merge(m, src)
}
func (m *MsgTransferResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("clairveil.privacy.v1.UserDisclosureMode", UserDisclosureMode_name, UserDisclosureMode_value)
	proto.RegisterType((*MsgDeposit)(nil), "clairveil.privacy.v1.MsgDeposit")
	proto.RegisterType((*MsgWithdraw)(nil), "clairveil.privacy.v1.MsgWithdraw")
	proto.RegisterType((*MsgTransfer)(nil), "clairveil.privacy.v1.MsgTransfer")
	proto.RegisterType((*MsgDepositResponse)(nil), "clairveil.privacy.v1.MsgDepositResponse")
	proto.RegisterType((*MsgWithdrawResponse)(nil), "clairveil.privacy.v1.MsgWithdrawResponse")
	proto.RegisterType((*MsgTransferResponse)(nil), "clairveil.privacy.v1.MsgTransferResponse")
}

func init() { proto.RegisterFile("clairveil/privacy/v1/tx.proto", fileDescriptor_cbddc2210f6432c2) }

var fileDescriptor_cbddc2210f6432c2 = []byte{
	// 827 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4d, 0x6f, 0xe3, 0x44,
	0x18, 0xae, 0xdb, 0xa6, 0x1f, 0x6f, 0xdd, 0x6c, 0x77, 0x36, 0xdb, 0xf5, 0x66, 0xb7, 0x26, 0x5b,
	0x09, 0x08, 0x15, 0x24, 0xea, 0x82, 0x10, 0xe2, 0xd6, 0x26, 0x16, 0x44, 0x34, 0x69, 0xe4, 0x26,
	0x02, 0xf6, 0x62, 0xb9, 0xf6, 0xd4, 0x19, 0x11, 0x7b, 0xac, 0x99, 0x71, 0x3e, 0x6e, 0x68, 0x7f,
	0x01, 0x37, 0x2e, 0xfc, 0x88, 0xfd, 0x07, 0x5c, 0xb9, 0x20, 0xed, 0x91, 0x23, 0x6a, 0x0f, 0xfb,
	0x37, 0x90, 0x27, 0xb1, 0x93, 0x38, 0xd9, 0xed, 0x85, 0x5b, 0xe6, 0xf9, 0x78, 0xfd, 0xbe, 0xcf,
	0x4c, 0x66, 0xe0, 0xc8, 0xe9, 0xdb, 0x84, 0x0d, 0x30, 0xe9, 0x57, 0x43, 0x46, 0x06, 0xb6, 0x33,
	0xae, 0x0e, 0x4e, 0xab, 0x62, 0x54, 0x09, 0x19, 0x15, 0x14, 0x15, 0x52, 0xba, 0x32, 0xa5, 0x2b,
	0x83, 0xd3, 0xe2, 0x13, 0x87, 0x72, 0x9f, 0xf2, 0xaa, 0xcf, 0xbd, 0x58, 0xed, 0x73, 0x6f, 0x22,
	0x3f, 0xfe, 0x43, 0x01, 0x68, 0x72, 0xaf, 0x8e, 0x43, 0xca, 0x89, 0x40, 0x1a, 0x6c, 0x3b, 0x0c,
	0xdb, 0x82, 0x32, 0x4d, 0x29, 0x29, 0xe5, 0x5d, 0x33, 0x59, 0xa2, 0x43, 0xd8, 0xb2, 0x7d, 0x1a,
	0x05, 0x42, 0x5b, 0x97, 0xc4, 0x74, 0x85, 0x3e, 0x85, 0x07, 0x01, 0x15, 0xd8, 0x72, 0xa8, 0xef,
	0x13, 0xe1, 0xe3, 0x40, 0x68, 0x1b, 0x25, 0xa5, 0xac, 0x9a, 0xf9, 0x18, 0xae, 0xa5, 0x28, 0xfa,
	0x18, 0xf2, 0x38, 0x70, 0xd8, 0x38, 0x14, 0xd8, 0xb5, 0x62, 0x4e, 0xdb, 0x94, 0xba, 0xfd, 0x14,
	0x6d, 0x51, 0x81, 0xbf, 0x55, 0x5f, 0xbf, 0x7b, 0x73, 0x92, 0x7c, 0xf5, 0xf8, 0xef, 0x75, 0xd8,
	0x6b, 0x72, 0xef, 0x47, 0x22, 0x7a, 0x2e, 0xb3, 0x87, 0x1f, 0xe8, 0xaf, 0x00, 0xb9, 0x90, 0x51,
	0x7a, 0x23, 0xdb, 0x53, 0xcd, 0xc9, 0x02, 0x21, 0xd8, 0x64, 0x94, 0x26, 0x2d, 0xc9, 0xdf, 0xe8,
	0x39, 0xec, 0x06, 0x51, 0xbf, 0x4f, 0x6e, 0x08, 0x66, 0xd3, 0x1e, 0x66, 0x00, 0xaa, 0xc0, 0xa3,
	0x00, 0x0f, 0xad, 0xec, 0x4c, 0x39, 0xa9, 0x7b, 0x18, 0xe0, 0x61, 0xeb, 0xbe, 0xb1, 0xb6, 0x56,
	0x8c, 0x35, 0x17, 0xdf, 0xf6, 0x42, 0x7c, 0xcf, 0x61, 0x97, 0x61, 0x87, 0x84, 0x24, 0xfe, 0xc8,
	0x8e, 0xa4, 0x66, 0x00, 0x7a, 0x0a, 0x3b, 0x4e, 0xcf, 0x26, 0x81, 0x45, 0x5c, 0x6d, 0x77, 0x3a,
	0x6f, 0xbc, 0x6e, 0xb8, 0xe8, 0x13, 0x78, 0x80, 0x47, 0x21, 0x61, 0x98, 0x5b, 0xb6, 0xb0, 0xa2,
	0x80, 0x8c, 0x34, 0x28, 0x29, 0xe5, 0x0d, 0x73, 0x7f, 0x0a, 0x9f, 0x89, 0x6e, 0x40, 0x46, 0x99,
	0x3c, 0xff, 0xcc, 0xc9, 0x3c, 0x3b, 0xcc, 0x0e, 0xf8, 0x0d, 0x66, 0xff, 0x4b, 0x9e, 0x3a, 0x40,
	0x1a, 0x1f, 0xd7, 0x36, 0x4b, 0x1b, 0x65, 0xd5, 0x9c, 0x43, 0xe4, 0x09, 0xc1, 0xc3, 0xb9, 0x30,
	0xb9, 0x96, 0x93, 0xa2, 0x7c, 0x80, 0x87, 0xb3, 0x24, 0x39, 0x7a, 0x01, 0xaa, 0x43, 0xc2, 0x1e,
	0x66, 0x96, 0xc0, 0x23, 0xc1, 0xb5, 0x2d, 0xa9, 0xda, 0x9b, 0x60, 0x9d, 0x18, 0x8a, 0x77, 0x27,
	0xe2, 0x98, 0x59, 0xd3, 0xa3, 0x6d, 0x85, 0xb4, 0x4f, 0x9c, 0xb1, 0xcc, 0x74, 0xdf, 0x7c, 0x18,
	0x53, 0xed, 0x09, 0xd3, 0x96, 0x04, 0xfa, 0x0a, 0x0e, 0xa5, 0xde, 0x25, 0xdc, 0xe9, 0x53, 0x1e,
	0x31, 0x6c, 0xb9, 0xc4, 0xc3, 0x7c, 0x92, 0xb5, 0x6a, 0x16, 0x62, 0xb6, 0x9e, 0x92, 0x75, 0xc9,
	0xa1, 0x57, 0x50, 0xc8, 0xba, 0x7c, 0xea, 0x62, 0xb9, 0x05, 0xf9, 0x97, 0xe5, 0xca, 0xaa, 0xbf,
	0x58, 0xa5, 0xbb, 0x50, 0xa9, 0x49, 0x5d, 0x6c, 0xa2, 0x68, 0x09, 0x43, 0x67, 0x70, 0x94, 0xad,
	0x2d, 0x6c, 0xe6, 0x61, 0x61, 0x85, 0xd1, 0xf5, 0x2f, 0x78, 0x2c, 0x77, 0x51, 0x35, 0x8b, 0x8b,
	0xd6, 0x8e, 0x94, 0xb4, 0xa5, 0x02, 0x7d, 0x0d, 0x4f, 0xb2, 0x25, 0x42, 0x7b, 0xdc, 0xa7, 0xb6,
	0xab, 0xed, 0x49, 0xf3, 0xe3, 0x45, 0x73, 0x7b, 0x42, 0xc6, 0x3e, 0x3b, 0x72, 0x89, 0x58, 0x91,
	0x86, 0x3a, 0xf1, 0x49, 0x7a, 0x29, 0x8e, 0x1a, 0xe8, 0x4b, 0xbe, 0xc5, 0x9e, 0xf7, 0xa5, 0xfd,
	0x59, 0xc6, 0xbe, 0xd0, 0xf4, 0x37, 0xa0, 0x2d, 0x15, 0x49, 0xba, 0xce, 0x4b, 0xfb, 0x61, 0xc6,
	0x3e, 0x6d, 0x3b, 0x73, 0x82, 0x0b, 0x80, 0x66, 0xf7, 0x95, 0x89, 0x79, 0x48, 0x03, 0x8e, 0x8f,
	0x1f, 0xc3, 0xa3, 0xb9, 0x6b, 0x22, 0x03, 0x27, 0xa7, 0x3d, 0x81, 0x4f, 0x5e, 0x2b, 0x80, 0x96,
	0xb7, 0x0b, 0x1d, 0xc1, 0xd3, 0xee, 0x95, 0x61, 0x5a, 0xf5, 0xc6, 0x55, 0xed, 0xe2, 0xf2, 0xaa,
	0x6b, 0x1a, 0x56, 0xf3, 0xb2, 0x6e, 0x58, 0xad, 0xcb, 0x96, 0x71, 0xb0, 0x86, 0x3e, 0x82, 0x67,
	0x2b, 0xe9, 0x76, 0xf7, 0xfc, 0xa2, 0x51, 0x3b, 0x50, 0xd0, 0xe7, 0x50, 0x5e, 0x29, 0x30, 0x8d,
	0x5a, 0xa3, 0xdd, 0x30, 0x5a, 0x1d, 0xcb, 0x68, 0xd5, 0xcc, 0x9f, 0xdb, 0x1d, 0xa3, 0x7e, 0xb0,
	0xfe, 0xf2, 0xf7, 0x75, 0xd8, 0x68, 0x72, 0x0f, 0x75, 0x61, 0x3b, 0xb9, 0x7d, 0x4b, 0xab, 0x4f,
	0xd6, 0x6c, 0xde, 0x62, 0xf9, 0x3e, 0x45, 0x32, 0x23, 0xfa, 0x09, 0x76, 0xd2, 0x5b, 0xf3, 0xc5,
	0x7b, 0x5d, 0x89, 0xa4, 0xf8, 0xd9, 0xbd, 0x92, 0xf9, 0xca, 0xe9, 0xfd, 0xf1, 0xfe, 0xca, 0x89,
	0xe4, 0x03, 0x95, 0xb3, 0xfb, 0x52, 0xcc, 0xfd, 0xfa, 0xee, 0xcd, 0x89, 0x72, 0xfe, 0xc3, 0x5f,
	0xb7, 0xba, 0xf2, 0xf6, 0x56, 0x57, 0xfe, 0xbd, 0xd5, 0x95, 0xdf, 0xee, 0xf4, 0xb5, 0xb7, 0x77,
	0xfa, 0xda, 0x3f, 0x77, 0xfa, 0xda, 0xab, 0x53, 0x8f, 0x88, 0x5e, 0x74, 0x5d, 0x71, 0xa8, 0x5f,
	0xad, 0x1b, 0x17, 0x8d, 0xef, 0xbe, 0xef, 0x7c, 0x71, 0x71, 0x76, 0x7e, 0x55, 0x9d, 0xbd, 0x89,
	0xa3, 0xf4, 0x55, 0x14, 0xe3, 0x10, 0xf3, 0xeb, 0x2d, 0xf9, 0xce, 0x7d, 0xf9, 0x5f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x81, 0x4a, 0x29, 0x78, 0x37, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// Deposit: 투명 자산 -> 익명 자산 (Note)
	Deposit(ctx context.Context, in *MsgDeposit, opts ...grpc.CallOption) (*MsgDepositResponse, error)
	// Withdraw: 익명 자산 -> 투명 자산
	Withdraw(ctx context.Context, in *MsgWithdraw, opts ...grpc.CallOption) (*MsgWithdrawResponse, error)
	// Transfer: shielded pool 내부 전송
	Transfer(ctx context.Context, in *MsgTransfer, opts ...grpc.CallOption) (*MsgTransferResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Deposit(ctx context.Context, in *MsgDeposit, opts ...grpc.CallOption) (*MsgDepositResponse, error) {
	out := new(MsgDepositResponse)
	err := c.cc.Invoke(ctx, "/clairveil.privacy.v1.Msg/Deposit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Withdraw(ctx context.Context, in *MsgWithdraw, opts ...grpc.CallOption) (*MsgWithdrawResponse, error) {
	out := new(MsgWithdrawResponse)
	err := c.cc.Invoke(ctx, "/clairveil.privacy.v1.Msg/Withdraw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Transfer(ctx context.Context, in *MsgTransfer, opts ...grpc.CallOption) (*MsgTransferResponse, error) {
	out := new(MsgTransferResponse)
	err := c.cc.Invoke(ctx, "/clairveil.privacy.v1.Msg/Transfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// Deposit: 투명 자산 -> 익명 자산 (Note)
	Deposit(context.Context, *MsgDeposit) (*MsgDepositResponse, error)
	// Withdraw: 익명 자산 -> 투명 자산
	Withdraw(context.Context, *MsgWithdraw) (*MsgWithdrawResponse, error)
	// Transfer: shielded pool 내부 전송
	Transfer(context.Context, *MsgTransfer) (*MsgTransferResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Deposit(ctx context.Context, req *MsgDeposit) (*MsgDepositResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deposit not implemented")
}
func (*UnimplementedMsgServer) Withdraw(ctx context.Context, req *MsgWithdraw) (*MsgWithdrawResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Withdraw not implemented")
}
func (*UnimplementedMsgServer) Transfer(ctx context.Context, req *MsgTransfer) (*MsgTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Transfer not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Deposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeposit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Deposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clairveil.privacy.v1.Msg/Deposit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Deposit(ctx, req.(*MsgDeposit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Withdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWithdraw)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Withdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clairveil.privacy.v1.Msg/Withdraw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Withdraw(ctx, req.(*MsgWithdraw))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTransfer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clairveil.privacy.v1.Msg/Transfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Transfer(ctx, req.(*MsgTransfer))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "clairveil.privacy.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deposit",
			Handler:    _Msg_Deposit_Handler,
		},
		{
			MethodName: "Withdraw",
			Handler:    _Msg_Withdraw_Handler,
		},
		{
			MethodName: "Transfer",
			Handler:    _Msg_Transfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clairveil/privacy/v1/tx.proto",
}

func (m *MsgDeposit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeposit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeposit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EncryptedNote) > 0 {
		i -= len(m.EncryptedNote)
		copy(dAtA[i:], m.EncryptedNote)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EncryptedNote)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.NoteCommitment) > 0 {
		i -= len(m.NoteCommitment)
		copy(dAtA[i:], m.NoteCommitment)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NoteCommitment)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgWithdraw) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdraw) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdraw) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExpiresAtUnix != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ExpiresAtUnix))
		i--
		dAtA[i] = 0x50
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.EncryptedNote) > 0 {
		i -= len(m.EncryptedNote)
		copy(dAtA[i:], m.EncryptedNote)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EncryptedNote)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.NewNoteCommitment) > 0 {
		i -= len(m.NewNoteCommitment)
		copy(dAtA[i:], m.NewNoteCommitment)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NewNoteCommitment)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Nullifier) > 0 {
		i -= len(m.Nullifier)
		copy(dAtA[i:], m.Nullifier)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Nullifier)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Root) > 0 {
		i -= len(m.Root)
		copy(dAtA[i:], m.Root)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Root)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Proof) > 0 {
		i -= len(m.Proof)
		copy(dAtA[i:], m.Proof)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Proof)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgTransfer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransfer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransfer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AuditDisclosurePayload) > 0 {
		i -= len(m.AuditDisclosurePayload)
		copy(dAtA[i:], m.AuditDisclosurePayload)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AuditDisclosurePayload)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.AuditDisclosureTargetPubkey) > 0 {
		i -= len(m.AuditDisclosureTargetPubkey)
		copy(dAtA[i:], m.AuditDisclosureTargetPubkey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AuditDisclosureTargetPubkey)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.AuditDisclosureDigest) > 0 {
		i -= len(m.AuditDisclosureDigest)
		copy(dAtA[i:], m.AuditDisclosureDigest)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AuditDisclosureDigest)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.UserDisclosurePayload) > 0 {
		i -= len(m.UserDisclosurePayload)
		copy(dAtA[i:], m.UserDisclosurePayload)
		i = encodeVarintTx(dAtA, i, uint64(len(m.UserDisclosurePayload)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.UserDisclosureTargetPubkey) > 0 {
		i -= len(m.UserDisclosureTargetPubkey)
		copy(dAtA[i:], m.UserDisclosureTargetPubkey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.UserDisclosureTargetPubkey)))
		i--
		dAtA[i] = 0x52
	}
	if m.UserDisclosureMode != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.UserDisclosureMode))
		i--
		dAtA[i] = 0x48
	}
	if len(m.UserDisclosureDigest) > 0 {
		i -= len(m.UserDisclosureDigest)
		copy(dAtA[i:], m.UserDisclosureDigest)
		i = encodeVarintTx(dAtA, i, uint64(len(m.UserDisclosureDigest)))
		i--
		dAtA[i] = 0x42
	}
	if m.UserPrivacyPolicy != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.UserPrivacyPolicy))
		i--
		dAtA[i] = 0x38
	}
	if len(m.CipherTexts) > 0 {
		for iNdEx := len(m.CipherTexts) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.CipherTexts[iNdEx])
			copy(dAtA[i:], m.CipherTexts[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.CipherTexts[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.NewCommitments) > 0 {
		for iNdEx := len(m.NewCommitments) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.NewCommitments[iNdEx])
			copy(dAtA[i:], m.NewCommitments[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.NewCommitments[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Nullifiers) > 0 {
		for iNdEx := len(m.Nullifiers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Nullifiers[iNdEx])
			copy(dAtA[i:], m.Nullifiers[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Nullifiers[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Root) > 0 {
		i -= len(m.Root)
		copy(dAtA[i:], m.Root)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Root)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Proof) > 0 {
		i -= len(m.Proof)
		copy(dAtA[i:], m.Proof)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Proof)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDepositResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDepositResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDepositResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgTransferResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransferResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransferResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgDeposit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.NoteCommitment)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.EncryptedNote)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgWithdraw) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Proof)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Root)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Nullifier)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.NewNoteCommitment)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.EncryptedNote)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ExpiresAtUnix != 0 {
		n += 1 + sovTx(uint64(m.ExpiresAtUnix))
	}
	return n
}

func (m *MsgTransfer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Proof)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Root)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Nullifiers) > 0 {
		for _, b := range m.Nullifiers {
			l = len(b)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.NewCommitments) > 0 {
		for _, b := range m.NewCommitments {
			l = len(b)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.CipherTexts) > 0 {
		for _, b := range m.CipherTexts {
			l = len(b)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if m.UserPrivacyPolicy != 0 {
		n += 1 + sovTx(uint64(m.UserPrivacyPolicy))
	}
	l = len(m.UserDisclosureDigest)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.UserDisclosureMode != 0 {
		n += 1 + sovTx(uint64(m.UserDisclosureMode))
	}
	l = len(m.UserDisclosureTargetPubkey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.UserDisclosurePayload)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AuditDisclosureDigest)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AuditDisclosureTargetPubkey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AuditDisclosurePayload)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDepositResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgWithdrawResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgTransferResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgDeposit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeposit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeposit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NoteCommitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NoteCommitment = append(m.NoteCommitment[:0], dAtA[iNdEx:postIndex]...)
			if m.NoteCommitment == nil {
				m.NoteCommitment = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncryptedNote", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EncryptedNote = append(m.EncryptedNote[:0], dAtA[iNdEx:postIndex]...)
			if m.EncryptedNote == nil {
				m.EncryptedNote = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdraw) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdraw: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdraw: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = append(m.Proof[:0], dAtA[iNdEx:postIndex]...)
			if m.Proof == nil {
				m.Proof = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Root = append(m.Root[:0], dAtA[iNdEx:postIndex]...)
			if m.Root == nil {
				m.Root = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nullifier", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nullifier = append(m.Nullifier[:0], dAtA[iNdEx:postIndex]...)
			if m.Nullifier == nil {
				m.Nullifier = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewNoteCommitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewNoteCommitment = append(m.NewNoteCommitment[:0], dAtA[iNdEx:postIndex]...)
			if m.NewNoteCommitment == nil {
				m.NewNoteCommitment = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncryptedNote", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EncryptedNote = append(m.EncryptedNote[:0], dAtA[iNdEx:postIndex]...)
			if m.EncryptedNote == nil {
				m.EncryptedNote = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAtUnix", wireType)
			}
			m.ExpiresAtUnix = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiresAtUnix |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTransfer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransfer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransfer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = append(m.Proof[:0], dAtA[iNdEx:postIndex]...)
			if m.Proof == nil {
				m.Proof = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Root = append(m.Root[:0], dAtA[iNdEx:postIndex]...)
			if m.Root == nil {
				m.Root = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nullifiers", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nullifiers = append(m.Nullifiers, make([]byte, postIndex-iNdEx))
			copy(m.Nullifiers[len(m.Nullifiers)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewCommitments", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewCommitments = append(m.NewCommitments, make([]byte, postIndex-iNdEx))
			copy(m.NewCommitments[len(m.NewCommitments)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CipherTexts", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CipherTexts = append(m.CipherTexts, make([]byte, postIndex-iNdEx))
			copy(m.CipherTexts[len(m.CipherTexts)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserPrivacyPolicy", wireType)
			}
			m.UserPrivacyPolicy = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserPrivacyPolicy |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserDisclosureDigest", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserDisclosureDigest = append(m.UserDisclosureDigest[:0], dAtA[iNdEx:postIndex]...)
			if m.UserDisclosureDigest == nil {
				m.UserDisclosureDigest = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserDisclosureMode", wireType)
			}
			m.UserDisclosureMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserDisclosureMode |= UserDisclosureMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserDisclosureTargetPubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserDisclosureTargetPubkey = append(m.UserDisclosureTargetPubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.UserDisclosureTargetPubkey == nil {
				m.UserDisclosureTargetPubkey = []byte{}
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserDisclosurePayload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserDisclosurePayload = append(m.UserDisclosurePayload[:0], dAtA[iNdEx:postIndex]...)
			if m.UserDisclosurePayload == nil {
				m.UserDisclosurePayload = []byte{}
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditDisclosureDigest", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuditDisclosureDigest = append(m.AuditDisclosureDigest[:0], dAtA[iNdEx:postIndex]...)
			if m.AuditDisclosureDigest == nil {
				m.AuditDisclosureDigest = []byte{}
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditDisclosureTargetPubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuditDisclosureTargetPubkey = append(m.AuditDisclosureTargetPubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.AuditDisclosureTargetPubkey == nil {
				m.AuditDisclosureTargetPubkey = []byte{}
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditDisclosurePayload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuditDisclosurePayload = append(m.AuditDisclosurePayload[:0], dAtA[iNdEx:postIndex]...)
			if m.AuditDisclosurePayload == nil {
				m.AuditDisclosurePayload = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDepositResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDepositResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDepositResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTransferResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransferResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransferResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
