#!/usr/bin/env bash

set -euo pipefail

resolve_gobin() {
	local gobin
	gobin="${GOBIN:-"$(go env GOBIN)"}"
	if [[ -z "$gobin" ]]; then
		gobin="$(go env GOPATH)/bin"
	fi
	printf '%s\n' "$gobin"
}

resolve_binary() {
	local env_value="$1"
	local name="$2"
	local gobin="$3"

	if [[ -n "$env_value" ]]; then
		printf '%s\n' "$env_value"
		return 0
	fi
	if [[ -x "$gobin/$name" ]]; then
		printf '%s\n' "$gobin/$name"
		return 0
	fi
	if command -v "$name" >/dev/null 2>&1; then
		command -v "$name"
		return 0
	fi

	echo "missing $name; run 'make install' first" >&2
	exit 1
}

backup_existing_home() {
	local home="$1"
	if [[ ! -e "$home" ]]; then
		return 0
	fi

	local timestamp backup candidate suffix
	timestamp="$(date +"%Y%m%d-%H%M%S")"
	backup="${home}.backup-${timestamp}"
	candidate="$backup"
	suffix=1
	while [[ -e "$candidate" ]]; do
		candidate="${backup}-${suffix}"
		suffix=$((suffix + 1))
	done

	mv "$home" "$candidate"
	echo "$candidate"
}

write_export_env_file() {
	local source_env="$1"
	local target_env="$2"

	{
		echo "# Source this file for strict ZK artifact preflight and privacy proof commands."
		echo "# Generated by scripts/init-localnet.sh."
		while IFS= read -r line; do
			if [[ -z "$line" || "$line" == \#* ]]; then
				continue
			fi
			echo "export $line"
		done <"$source_env"
		echo "export CLAIRVEIL_PRIVACY_ZK_PREFLIGHT_MODE=strict"
	} >"$target_env"
}

patch_genesis_audit_key() {
	local home="$1"
	local auditor_hex_file="$2"

	python3 - "$home" "$auditor_hex_file" <<'PY'
import base64
import json
import sys
from pathlib import Path

home = Path(sys.argv[1])
auditor_hex = Path(sys.argv[2]).read_text().strip()
genesis_path = home / "config" / "genesis.json"
doc = json.loads(genesis_path.read_text())
doc["app_state"]["privacy"]["audit_master_pubkey"] = base64.b64encode(bytes.fromhex(auditor_hex)).decode()
genesis_path.write_text(json.dumps(doc, indent=2))
PY
}

home="${CLAIRVEIL_HOME:-"$HOME/.clairveil"}"
chain_id="${CHAIN_ID:-clairveil-local-1}"
node_name="${NODE_NAME:-local}"
keyring_backend="${KEYRING_BACKEND:-test}"
fund_amount="${FUND_AMOUNT:-100000000000000000000uclair}"
stake_amount="${STAKE_AMOUNT:-9000000000000000000uclair}"
accounts_raw="${CLAIRVEIL_INIT_ACCOUNTS:-alice bob relayer auditor}"
validator_key="${VALIDATOR_KEY:-alice}"
auditor_key="${AUDITOR_KEY:-auditor}"
gobin="$(resolve_gobin)"
clairveild="$(resolve_binary "${CLAIRVEILD_BIN:-}" clairveild "$gobin")"
clairveil_setup="$(resolve_binary "${CLAIRVEIL_SETUP_BIN:-}" clairveil-setup "$gobin")"

backup_path="$(backup_existing_home "$home" || true)"
mkdir -p "$home"

out="$home/init-out"
artifacts="${CLAIRVEIL_PRIVACY_ZK_ARTIFACT_DIR:-"$home/artifacts/privacy"}"
env_file="$home/clairveil.env"
mkdir -p "$out" "$artifacts"

run() {
	"$clairveild" "$@"
}

echo "initializing Clairveil local home: $home"
if [[ -n "$backup_path" ]]; then
	echo "previous home backup: $backup_path"
fi

"$clairveil_setup" --out "$artifacts" >"$out/setup.stdout" 2>"$out/setup.stderr"

read -r -a accounts <<<"$accounts_raw"
if [[ "${#accounts[@]}" -eq 0 ]]; then
	echo "CLAIRVEIL_INIT_ACCOUNTS must contain at least one key" >&2
	exit 1
fi

has_validator=0
has_auditor=0
for account in "${accounts[@]}"; do
	if [[ "$account" == "$validator_key" ]]; then
		has_validator=1
	fi
	if [[ "$account" == "$auditor_key" ]]; then
		has_auditor=1
	fi
done
if [[ "$has_validator" != "1" ]]; then
	echo "VALIDATOR_KEY must be included in CLAIRVEIL_INIT_ACCOUNTS" >&2
	exit 1
fi
if [[ "$has_auditor" != "1" ]]; then
	echo "AUDITOR_KEY must be included in CLAIRVEIL_INIT_ACCOUNTS" >&2
	exit 1
fi

for account in "${accounts[@]}"; do
	run keys add "$account" --keyring-backend "$keyring_backend" --home "$home" --output json >"$out/${account}-key.json"
	run keys show -a "$account" --keyring-backend "$keyring_backend" --home "$home" >"$out/${account}-address.txt"
done

run tx privacy show-disclosure-pubkey --from "$auditor_key" --keyring-backend "$keyring_backend" --home "$home" --output json >"$out/auditor-disclosure.json"
python3 - "$out/auditor-disclosure.json" "$out/auditor-disclosure.hex" <<'PY'
import json
import sys
from pathlib import Path

data = json.loads(Path(sys.argv[1]).read_text())
Path(sys.argv[2]).write_text(data["public_key_hex"] + "\n")
PY

run init "$node_name" --chain-id "$chain_id" --home "$home" >"$out/init.stdout" 2>"$out/init.stderr"

for account in "${accounts[@]}"; do
	run add-genesis-account "$account" "$fund_amount" --keyring-backend "$keyring_backend" --home "$home" >"$out/add-${account}.stdout" 2>"$out/add-${account}.stderr"
done

run gentx "$validator_key" "$stake_amount" --chain-id "$chain_id" --keyring-backend "$keyring_backend" --home "$home" >"$out/gentx.stdout" 2>"$out/gentx.stderr"
run collect-gentxs --home "$home" >"$out/collect-gentxs.stdout" 2>"$out/collect-gentxs.stderr"
patch_genesis_audit_key "$home" "$out/auditor-disclosure.hex"
run validate --home "$home" >"$out/validate.stdout" 2>"$out/validate.stderr"

write_export_env_file "$artifacts/privacy_zk_checksums.env" "$env_file"

echo "initialized: $home"
echo "chain-id: $chain_id"
echo "validator key: $validator_key"
echo "auditor key: $auditor_key"
echo "keyring backend: $keyring_backend"
echo "zk artifacts: $artifacts"
echo "env file: $env_file"
echo
echo "Start with default warn-mode preflight:"
echo "  clairveild start"
echo
echo "Start with strict ZK artifact preflight:"
echo "  source $env_file && clairveild start"
